// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Reflection;
using System.Text;

using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators.Helpers;

/// <summary>
/// Provides methods to read embedded attribute source files and transform them
/// into emittable source code suitable for injection into consuming compilations.
/// </summary>
internal static class AttributeSourceRewriter
{
	private static readonly Assembly ResourceAssembly = typeof(AttributeSourceRewriter).Assembly;

	/// <summary>
	/// A mapping of simple type names (from <c>using</c> directives) to their fully qualified equivalents
	/// prefixed with <c>global::</c>.
	/// </summary>
	private static readonly Dictionary<string, string> KnownTypeReplacements = new()
	{
		["Type"] = "global::System.Type",
		["Attribute"] = "global::System.Attribute",
		["AttributeUsage"] = "global::System.AttributeUsage",
		["AttributeUsageAttribute"] = "global::System.AttributeUsageAttribute",
		["AttributeTargets"] = "global::System.AttributeTargets",
		["INotifyPropertyChanging"] = "global::System.ComponentModel.INotifyPropertyChanging",
		["INotifyPropertyChanged"] = "global::System.ComponentModel.INotifyPropertyChanged",
	};

	/// <summary>
	/// Reads the specified embedded resource and transforms it into source code
	/// that can be emitted by a source generator.
	/// </summary>
	/// <param name="resourceName">The logical name of the embedded resource.</param>
	/// <returns>The transformed source code string ready for emission.</returns>
	public static string ReadAndTransform(string resourceName)
	{
		string source = ReadEmbeddedResource(resourceName);
		return TransformSource(source);
	}

	private static string ReadEmbeddedResource(string resourceName)
	{
		using Stream stream = ResourceAssembly.GetManifestResourceStream(resourceName);
		using StreamReader reader = new(stream);
		return reader.ReadToEnd();
	}

	private static string TransformSource(string source)
	{
		SyntaxTree tree = CSharpSyntaxTree.ParseText(source);
		CompilationUnitSyntax root = tree.GetCompilationUnitRoot();

		HashSet<string> importedNames = [];
		foreach (UsingDirectiveSyntax usingDirective in root.Usings)
		{
			string ns = usingDirective.Name?.ToString() ?? string.Empty;
			if (ns.Equals("System", StringComparison.Ordinal))
			{
				importedNames.Add("Type");
				importedNames.Add("Attribute");
				importedNames.Add("AttributeUsage");
				importedNames.Add("AttributeUsageAttribute");
				importedNames.Add("AttributeTargets");
			}
			else if (ns.Equals("System.ComponentModel", StringComparison.Ordinal))
			{
				importedNames.Add("INotifyPropertyChanging");
				importedNames.Add("INotifyPropertyChanged");
			}
		}

		Rewriter rewriter = new(importedNames);
		SyntaxNode transformed = rewriter.Visit(root);

		StringBuilder sb = new();
		sb.AppendAutoGeneratedWarning(typeof(AttributeSourceGenerator).FullName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.Append(transformed.NormalizeWhitespace().ToFullString());

		return sb.ToString();
	}

	/// <summary>
	/// A syntax rewriter that transforms attribute source code for emission.
	/// </summary>
	private sealed class Rewriter(HashSet<string> importedNames) : CSharpSyntaxRewriter
	{
		/// <summary>
		/// Removes all using directives since the emitted code uses fully qualified names.
		/// </summary>
		public override SyntaxNode? VisitUsingDirective(UsingDirectiveSyntax node)
			=> null;

		/// <summary>
		/// Converts file-scoped namespace declarations to block-scoped namespace declarations.
		/// </summary>
		public override SyntaxNode? VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
		{
			NamespaceDeclarationSyntax blockNamespace = SyntaxFactory.NamespaceDeclaration(node.Name)
				.WithMembers(node.Members)
				.WithLeadingTrivia(node.GetLeadingTrivia())
				.WithTrailingTrivia(node.GetTrailingTrivia());

			return Visit(blockNamespace);
		}

		/// <summary>
		/// Changes <c>public</c> to <c>internal</c> on class declarations.
		/// </summary>
		public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
		{
			node = ReplaceAccessibility(node);
			return base.VisitClassDeclaration(node);
		}

		/// <summary>
		/// Removes license header comments from the compilation unit.
		/// </summary>
		public override SyntaxNode? VisitCompilationUnit(CompilationUnitSyntax node)
		{
			SyntaxTriviaList leadingTrivia = node.GetLeadingTrivia();
			SyntaxTriviaList filtered = RemoveLicenseHeader(leadingTrivia);
			node = node.WithLeadingTrivia(filtered);
			return base.VisitCompilationUnit(node);
		}

		/// <summary>
		/// Fully qualifies simple type names that were imported via <c>using</c> directives.
		/// </summary>
		public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
		{
			string name = node.Identifier.ValueText;

			return importedNames.Contains(name) && KnownTypeReplacements.TryGetValue(name, out string? replacement)
				? SyntaxFactory.ParseTypeName(replacement)
					.WithLeadingTrivia(node.GetLeadingTrivia())
					.WithTrailingTrivia(node.GetTrailingTrivia())
				: base.VisitIdentifierName(node);
		}

		/// <summary>
		/// Converts primary constructors to traditional constructors with explicit properties.
		/// </summary>
		public override SyntaxNode? VisitParameterList(ParameterListSyntax node)
		{
			return node.Parent is ClassDeclarationSyntax ? base.VisitParameterList(node) : base.VisitParameterList(node);
		}

		private static ClassDeclarationSyntax ReplaceAccessibility(ClassDeclarationSyntax node)
		{
			SyntaxTokenList modifiers = node.Modifiers;
			SyntaxTokenList newModifiers = [];

			foreach (SyntaxToken modifier in modifiers)
			{
				if (modifier.IsKind(SyntaxKind.PublicKeyword))
				{
					SyntaxToken internalToken = SyntaxFactory.Token(SyntaxKind.InternalKeyword)
						.WithLeadingTrivia(modifier.LeadingTrivia)
						.WithTrailingTrivia(modifier.TrailingTrivia);
					newModifiers = newModifiers.Add(internalToken);
				}
				else
				{
					newModifiers = newModifiers.Add(modifier);
				}
			}

			return node.WithModifiers(newModifiers);
		}

		private static SyntaxTriviaList RemoveLicenseHeader(SyntaxTriviaList trivia)
		{
			List<SyntaxTrivia> result = [];
			bool headerEnded = false;

			foreach (SyntaxTrivia t in trivia)
			{
				if (!headerEnded)
				{
					if (t.IsKind(SyntaxKind.SingleLineCommentTrivia))
						continue;
					if (t.IsKind(SyntaxKind.EndOfLineTrivia))
						continue;

					headerEnded = true;
				}

				result.Add(t);
			}

			return SyntaxFactory.TriviaList(result);
		}
	}
}
