// Copyright: 2025 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using Microsoft.CodeAnalysis;

namespace BB84.SourceGenerators.Generators;

/// <summary>
/// A source generator that emits the attribute source code into the consuming project's compilation
/// so that the attributes are available without requiring a direct assembly reference.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AttributeSourceGenerator : IIncrementalGenerator
{
	private const string GenerateAbstractionAttributeSource =
		"""
    // <auto-generated/>
    #nullable enable

    namespace BB84.SourceGenerators.Attributes
    {
      /// <summary>
      /// Represents an attribute that indicates a static class should have an abstraction generated for it.
      /// </summary>
      [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
      internal sealed class GenerateAbstractionAttribute : global::System.Attribute
      {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateAbstractionAttribute"/> class.
        /// </summary>
        /// <param name="targetType">The type of the static class to generate an abstraction for.</param>
        /// <param name="abstractionType">The type of the generated abstraction.</param>
        /// <param name="implementationType">The type of the generated implementation.</param>
        public GenerateAbstractionAttribute(global::System.Type targetType, global::System.Type abstractionType, global::System.Type implementationType)
        {
          TargetType = targetType;
          AbstractionType = abstractionType;
          ImplementationType = implementationType;
          ExcludeMethods = new string[0];
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateAbstractionAttribute"/> class.
        /// </summary>
        /// <param name="targetType">The type of the static class to generate an abstraction for.</param>
        /// <param name="abstractionType">The type of the generated abstraction.</param>
        /// <param name="implementationType">The type of the generated implementation.</param>
        /// <param name="excludeMethods">The methods to exclude from the generated abstraction.</param>
        public GenerateAbstractionAttribute(global::System.Type targetType, global::System.Type abstractionType, global::System.Type implementationType, params string[] excludeMethods)
        {
          TargetType = targetType;
          AbstractionType = abstractionType;
          ImplementationType = implementationType;
          ExcludeMethods = excludeMethods;
        }

        /// <summary>
        /// Gets the type of the static class to generate an abstraction for.
        /// </summary>
        public global::System.Type TargetType { get; }

        /// <summary>
        /// Gets the type of the generated abstraction.
        /// </summary>
        public global::System.Type AbstractionType { get; }

        /// <summary>
        /// Gets the type of the generated implementation.
        /// </summary>
        public global::System.Type ImplementationType { get; }

        /// <summary>
        /// Gets the methods to exclude from the generated abstraction.
        /// </summary>
        public string[] ExcludeMethods { get; }
      }
    }
    """;

	private const string GenerateEnumeratorExtensionsAttributeSource =
		"""
    // <auto-generated/>
    #nullable enable

    namespace BB84.SourceGenerators.Attributes
    {
      /// <summary>
      /// Indicates that the decorated enumeration should have extension methods generated.
      /// </summary>
      [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
      internal sealed class GenerateEnumeratorExtensionsAttribute : global::System.Attribute
      {
      }
    }
    """;

	private const string GenerateNotificationsAttributeSource =
		"""
    // <auto-generated/>
    #nullable enable

    namespace BB84.SourceGenerators.Attributes
    {
      /// <summary>
      /// Indicates that the decorated class should have properties with changing and changed
      /// notifications generated for its fields.
      /// </summary>
      [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
      internal sealed class GenerateNotificationsAttribute : global::System.Attribute
      {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateNotificationsAttribute"/> class.
        /// </summary>
        /// <param name="isChanged">
        /// Indicates whether a boolean property named <c>IsChanged</c> should be generated.
        /// </param>
        public GenerateNotificationsAttribute(bool isChanged = false)
        {
          IsChanged = isChanged;
        }

        /// <summary>
        /// Indicates whether a boolean property named <c>IsChanged</c> should be generated.
        /// </summary>
        public bool IsChanged { get; }
      }
    }
    """;

	/// <inheritdoc />
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static ctx =>
		{
			ctx.AddSource("GenerateAbstractionAttribute.g.cs", GenerateAbstractionAttributeSource);
			ctx.AddSource("GenerateEnumeratorExtensionsAttribute.g.cs", GenerateEnumeratorExtensionsAttributeSource);
			ctx.AddSource("GenerateNotificationsAttribute.g.cs", GenerateNotificationsAttributeSource);
		});
	}
}
