// Copyright: 2025 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Generators.Base;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators.Generators;

/// <summary>
/// Responsible for generating notification properties for classes marked
/// with the <see cref="GenerateNotificationsAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NotificationPropertiesGenerator : AttributeBasedGenerator<GenerateNotificationsAttribute>
{
	/// <inheritdoc/>
	public override string GeneratorName => "BB84.SourceGenerators.NotificationPropertiesGenerator";

	/// <inheritdoc/>
	protected override bool Predicate(SyntaxNode node)
			=> node is ClassDeclarationSyntax;

	/// <inheritdoc/>
	protected override SyntaxNode Transform(SyntaxNode targetNode)
			=> (ClassDeclarationSyntax)targetNode;

	/// <inheritdoc/>
	protected override void Execute(SourceProductionContext context, SyntaxNode syntaxNode)
	{
		ClassDeclarationSyntax classDeclaration = (ClassDeclarationSyntax)syntaxNode;

		bool generateIsChanged = GetGenerateIsChanged(classDeclaration);

		List<FieldDeclarationSyntax> members = [.. classDeclaration.Members
						.OfType<FieldDeclarationSyntax>()
						.Where(field => field is not null)];

		// fetch the field name and declaration type
		string className = classDeclaration.Identifier.Text;
		string namespaceName = classDeclaration.GetNamespace();

		StringBuilder sb = new();
		
		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		AppendUsings(sb);
		AppendNamespaceStart(namespaceName, sb);
		AppendClassStart(className, generateIsChanged, sb);

		sb.AppendLine(string.Join(Environment.NewLine, members.SelectMany(member =>
				member.Declaration.Variables.Select(variable =>
				{
					string fieldName = variable.Identifier.Text;
					string fieldType = $"{member.Declaration.Type}";
					string propertyName = FieldNameToPropertyName(fieldName);

					return $@"
				public {fieldType} {propertyName}
				{{
						get => {fieldName};
						set
						{{
								if (!Equals({fieldName}, value))
								{{
										RaisePropertyChanging(nameof({propertyName}));
										{fieldName} = value;
										RaisePropertyChanged(nameof({propertyName}));
										{(generateIsChanged ? "IsChanged = true;" : string.Empty)}
								}}
						}}
				}}";
				}))));

		AppendClassEnd(sb);
		AppendNamespaceEnd(sb);

		string sourceText = sb.ToString();
		context.AddSource($"{className}.g.cs", sourceText);
	}

	private static bool GetGenerateIsChanged(ClassDeclarationSyntax classDeclaration)
	{
		return classDeclaration.AttributeLists
				.SelectMany(attributeList => attributeList.Attributes)
				.Where(attribute => attribute.Name.ToString() == "GenerateNotifications")
				.Select(attribute => attribute.ArgumentList?.Arguments.FirstOrDefault())
				.Where(argument => argument != null)
				.Select(argument => bool.TryParse(argument?.ToString(), out bool result) && result)
				.FirstOrDefault();
	}

	private static void AppendClassEnd(StringBuilder sourceBuilder)
	{
		sourceBuilder.AppendLine("        /// <summary>");
		sourceBuilder.AppendLine("        /// Raises the <see cref=\"PropertyChanging\"/> event to notify subscribers that a property");
		sourceBuilder.AppendLine("        /// is about to change.");
		sourceBuilder.AppendLine("        /// </summary>");
		sourceBuilder.AppendLine("        /// <param name=\"propertyName\">The name of the property that is changing.</param>");
		sourceBuilder.AppendLine("        protected virtual void RaisePropertyChanging(string propertyName)");
		sourceBuilder.AppendLine("            => PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));");
		sourceBuilder.AppendLine();
		sourceBuilder.AppendLine("        /// <summary>");
		sourceBuilder.AppendLine("        /// Raises the <see cref=\"PropertyChanged\"/> event to notify subscribers that a property");
		sourceBuilder.AppendLine("        /// has changed.");
		sourceBuilder.AppendLine("        /// </summary>");
		sourceBuilder.AppendLine("        /// <param name=\"propertyName\">The name of the property that has changed.</param>");
		sourceBuilder.AppendLine("        protected virtual void RaisePropertyChanged(string propertyName)");
		sourceBuilder.AppendLine("            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
		sourceBuilder.AppendLine("    }");
	}

	private static void AppendClassStart(string className, bool generateIsChanged, StringBuilder sourceBuilder)
	{
		sourceBuilder.AppendLine($"    public partial class {className} : INotifyPropertyChanged, INotifyPropertyChanging");
		sourceBuilder.AppendLine("    {");
		sourceBuilder.AppendLine("        /// <inheritdoc/>");
		sourceBuilder.AppendLine("        public event PropertyChangedEventHandler? PropertyChanged;");
		sourceBuilder.AppendLine();
		sourceBuilder.AppendLine("        /// <inheritdoc/>");
		sourceBuilder.AppendLine("        public event PropertyChangingEventHandler? PropertyChanging;");
		sourceBuilder.AppendLine();
		if (generateIsChanged)
		{
			sourceBuilder.AppendLine("        private bool _isChanged;");
			sourceBuilder.AppendLine();
			sourceBuilder.AppendLine("        /// <summary>");
			sourceBuilder.AppendLine("        /// Gets or sets a value indicating whether the object has been changed.");
			sourceBuilder.AppendLine("        /// </summary>");
			sourceBuilder.AppendLine("        public bool IsChanged");
			sourceBuilder.AppendLine("        {");
			sourceBuilder.AppendLine("            get => _isChanged;");
			sourceBuilder.AppendLine("            set");
			sourceBuilder.AppendLine("            {");
			sourceBuilder.AppendLine("                if (_isChanged != value)");
			sourceBuilder.AppendLine("                {");
			sourceBuilder.AppendLine("                    RaisePropertyChanging(nameof(IsChanged));");
			sourceBuilder.AppendLine("                    _isChanged = value;");
			sourceBuilder.AppendLine("                    RaisePropertyChanged(nameof(IsChanged));");
			sourceBuilder.AppendLine("                }");
			sourceBuilder.AppendLine("            }");
			sourceBuilder.AppendLine("        }");
			sourceBuilder.AppendLine();
		}
	}

	private static void AppendNamespaceEnd(StringBuilder sourceBuilder)
	{
		sourceBuilder.AppendLine("}");
	}

	private static void AppendNamespaceStart(string classNamespace, StringBuilder sourceBuilder)
	{
		sourceBuilder.AppendLine($"namespace {classNamespace}");
		sourceBuilder.AppendLine("{");
	}

	private static void AppendUsings(StringBuilder sourceBuilder)
	{
		sourceBuilder.AppendLine("using System;");
		sourceBuilder.AppendLine("using System.ComponentModel;");
		sourceBuilder.AppendLine();
	}

	/// <summary>
	/// Converts a field name to a property name by removing any leading underscores
	/// and capitalizing the first letter.
	/// </summary>
	/// <param name="fieldName">The field name to convert.</param>
	/// <returns>The converted property name.</returns>
	private static string FieldNameToPropertyName(string fieldName)
	{
		if (fieldName.StartsWith("_", StringComparison.OrdinalIgnoreCase))
			fieldName = fieldName[1..];
		return $"{char.ToUpperInvariant(fieldName[0])}{fieldName[1..]}";
	}
}
