// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

namespace BB84.SourceGenerators.Extensions;

/// <summary>
/// The extensions for <see cref="StringBuilder"/> to append an auto-generated warning comment.
/// </summary>
internal static class StringBuilderExtensions
{
	/// <summary>
	/// Adds an auto-generated warning comment to the <see cref="StringBuilder"/>.
	/// </summary>
	/// <param name="stringBuilder">The <see cref="StringBuilder"/> to which the warning will be appended.</param>
	/// <param name="toolName">The name of the tool that generated the code.</param>
	/// <returns>The same <see cref="StringBuilder"/> instance with the auto-generated warning appended.</returns>
	public static StringBuilder AppendAutoGeneratedWarning(this StringBuilder stringBuilder, string toolName)
	{
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");
		stringBuilder.AppendLine("// <auto-generated>");
		stringBuilder.AppendLine("//     This code was generated by a tool.");
		stringBuilder.AppendLine($"//     Tool: {toolName}");
		stringBuilder.AppendLine("//");
		stringBuilder.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
		stringBuilder.AppendLine("//     the code is regenerated.");
		stringBuilder.AppendLine("// </auto-generated>");
		stringBuilder.AppendLine("//------------------------------------------------------------------------------");

		return stringBuilder;
	}
}
