// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Requests;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Represents a source generator that generates abstractions for static classes.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AbstractionGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(AbstractionGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateAbstractionAttribute).FullName;

	/// <inheritdoc />
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<AbstractionRequest?> abstractionRequests =
				context.SyntaxProvider.CreateSyntaxProvider(
						predicate: static (node, _) => IsCandidateClassNode(node),
						transform: static (ctx, ct) => CreateAbstractionRequest(ctx, ct))
				.Where(static r => r is not null);

		context.RegisterSourceOutput(abstractionRequests, static (spc, request) =>
		{
			if (request is null)
				return;

			spc.AddSource($"{request.AbstractionType.Name}.g.cs", GenerateAbstractionSource(request));
			spc.AddSource($"{request.ImplementationType.Name}.g.cs", GenerateImplementationSource(request));
		});
	}

	/// <summary>
	/// Generates the source code for the abstraction interface based on the given request.
	/// </summary>
	/// <param name="request">
	/// The abstraction request containing information about the target type and generated abstraction.
	/// </param>
	/// <returns>
	/// The generated source code for the abstraction interface.
	/// </returns>
	private static string GenerateAbstractionSource(AbstractionRequest request)
	{
		IEnumerable<IPropertySymbol> propertySymbols = GetPropertySymbols(request);
		HashSet<string> propertyAccessorNames = GetPropertyAccessorNames(propertySymbols);
		IEnumerable<IMethodSymbol> methodSymbols = GetMethodSymbols(request, propertyAccessorNames);

		string abstractionNamespace = GetFullNamespace(request.AbstractionType);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine($"namespace {abstractionNamespace}");
		sb.AppendLine("{");
		sb.AppendLine($"  {GetAccessibilityKeyword(request.AbstractionType.DeclaredAccessibility)} partial interface {request.AbstractionType.Name}");
		sb.AppendLine("  {");
		foreach (IPropertySymbol propertySymbol in propertySymbols)
		{
			sb.AppendLine($"    {CreatePropertyComment(request, propertySymbol)}");
			sb.AppendLine($"    {CreateAbstractionPropertySignature(propertySymbol)}");
		}
		foreach (IMethodSymbol methodSymbol in methodSymbols)
		{
			sb.AppendLine($"    {CreateMethodComment(request, methodSymbol)}");
			sb.AppendLine($"    {CreateMethodSignature(methodSymbol)};");
		}
		sb.AppendLine("  }");
		sb.AppendLine("}");

		return sb.ToString();
	}

	private static string GenerateImplementationSource(AbstractionRequest request)
	{
		IEnumerable<IPropertySymbol> propertySymbols = GetPropertySymbols(request);
		HashSet<string> propertyAccessorNames = GetPropertyAccessorNames(propertySymbols);
		IEnumerable<IMethodSymbol> methodSymbols = GetMethodSymbols(request, propertyAccessorNames);

		string abstractionNamespace = GetFullNamespace(request.AbstractionType);
		string implementationNamespace = GetFullNamespace(request.ImplementationType);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		if (abstractionNamespace != implementationNamespace)
		{
			sb.AppendLine($"using {abstractionNamespace};");
			sb.AppendLine();
		}
		sb.AppendLine($"namespace {implementationNamespace}");
		sb.AppendLine("{");
		sb.AppendLine($"  {GetAccessibilityKeyword(request.ImplementationType.DeclaredAccessibility)} partial class {request.ImplementationType.Name} : {request.AbstractionType.Name}");
		sb.AppendLine("  {");
		foreach (IPropertySymbol propertySymbol in propertySymbols)
		{
			sb.AppendLine($"    {CreatePropertyComment(request, propertySymbol)}");
			sb.AppendLine($"    {CreateImplementationPropertySignature(request, propertySymbol)}");
		}
		foreach (IMethodSymbol methodSymbol in methodSymbols)
		{
			sb.AppendLine($"    public {CreateMethodSignature(methodSymbol)}");
			sb.AppendLine($"      => {CreateMethodUsing(request, methodSymbol)};");
		}
		sb.AppendLine("  }");
		sb.AppendLine("}");
		return sb.ToString();
	}

	/// <summary>
	/// Gets the public static property symbols from the target type, excluding any properties in the exclusion list.
	/// </summary>
	/// <param name="request">The abstraction request containing the target type and exclusion information.</param>
	/// <returns>An enumerable of public static property symbols.</returns>
	private static IEnumerable<IPropertySymbol> GetPropertySymbols(AbstractionRequest request)
		=> request.TargetType
			.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.DeclaredAccessibility == Accessibility.Public && p.IsStatic && !request.ExcludeProperties.Contains(p.Name));

	/// <summary>
	/// Gets the set of property accessor method names (e.g. get_PropertyName, set_PropertyName)
	/// for the given property symbols, so they can be filtered from method generation.
	/// </summary>
	/// <param name="propertySymbols">The property symbols to extract accessor names from.</param>
	/// <returns>A set of accessor method names.</returns>
	private static HashSet<string> GetPropertyAccessorNames(IEnumerable<IPropertySymbol> propertySymbols)
	{
		HashSet<string> names = [];
		foreach (IPropertySymbol property in propertySymbols)
		{
			if (property.GetMethod != null)
				names.Add(property.GetMethod.Name);
			if (property.SetMethod != null)
				names.Add(property.SetMethod.Name);
		}
		return names;
	}

	/// <summary>
	/// Gets the public static method symbols from the target type, excluding any methods in the exclusion list
	/// and any property accessor methods.
	/// </summary>
	/// <param name="request">The abstraction request containing the target type and exclusion information.</param>
	/// <param name="propertyAccessorNames">The set of property accessor method names to exclude.</param>
	/// <returns>An enumerable of public static method symbols.</returns>
	private static IEnumerable<IMethodSymbol> GetMethodSymbols(AbstractionRequest request, HashSet<string> propertyAccessorNames)
		=> request.TargetType
			.GetMembers()
			.OfType<IMethodSymbol>()
			.Where(m => m.DeclaredAccessibility == Accessibility.Public && m.IsStatic
				&& !request.ExcludeMethods.Contains(m.Name)
				&& !propertyAccessorNames.Contains(m.Name));

	/// <summary>
	/// Creates a string representation of the specified method symbol, including its name and parameter list.
	/// </summary>
	/// <param name="request">The abstraction request containing the target type information.</param>
	/// <param name="methodSymbol">The method symbol to represent. Must not be <c>null</c>.</param>
	/// <returns>
	/// A string containing the method's name followed by its parameter names in parentheses, separated by commas.
	/// </returns>
	private static string CreateMethodUsing(AbstractionRequest request, IMethodSymbol methodSymbol)
	{
		IEnumerable<string> parameters = methodSymbol.Parameters.Select(p => $"{GetCallSiteModifier(p)}{p.Name}");
		return $"{request.TargetType}.{methodSymbol.Name}({string.Join(", ", parameters)})";
	}

	/// <summary>
	/// Creates a string representation of a method signature, including its return type, name, and parameter list.
	/// </summary>
	/// <param name="methodSymbol">
	/// The symbol representing the method to generate the signature for. Must not be <c>null</c>.
	/// </param>
	/// <returns>
	/// A string containing the method's signature in the format: "ReturnType MethodName(Type1 param1, Type2 param2, ...);".
	/// </returns>
	private static string CreateMethodSignature(IMethodSymbol methodSymbol)
	{
		IEnumerable<string> parameters = methodSymbol.Parameters.Select(p => $"{GetParameterModifier(p)}{p.Type} {p.Name}");
		return $"{methodSymbol.ReturnType} {methodSymbol.Name}({string.Join(", ", parameters)})";
	}

	/// <summary>
	/// Creates a property signature for the abstraction interface, including the getter and/or setter.
	/// </summary>
	/// <param name="propertySymbol">The property symbol to generate the signature for.</param>
	/// <returns>A string containing the property signature for the abstraction interface.</returns>
	private static string CreateAbstractionPropertySignature(IPropertySymbol propertySymbol)
	{
		string accessors = GetPropertyAccessors(propertySymbol);
		return $"{propertySymbol.Type} {propertySymbol.Name} {{ {accessors} }}";
	}

	/// <summary>
	/// Creates a property implementation that delegates to the target static class.
	/// </summary>
	/// <param name="request">The abstraction request containing the target type information.</param>
	/// <param name="propertySymbol">The property symbol to generate the implementation for.</param>
	/// <returns>A string containing the property implementation.</returns>
	private static string CreateImplementationPropertySignature(AbstractionRequest request, IPropertySymbol propertySymbol)
	{
		string getter = propertySymbol.GetMethod != null && propertySymbol.GetMethod.DeclaredAccessibility == Accessibility.Public
			? $"get => {request.TargetType}.{propertySymbol.Name};"
			: string.Empty;
		string setter = propertySymbol.SetMethod != null && propertySymbol.SetMethod.DeclaredAccessibility == Accessibility.Public
			? $"set => {request.TargetType}.{propertySymbol.Name} = value;"
			: string.Empty;
		return $"public {propertySymbol.Type} {propertySymbol.Name} {{{getter}{setter}}}";
	}

	/// <summary>
	/// Gets the accessor string (get; set;) for the given property symbol.
	/// </summary>
	/// <param name="propertySymbol">The property symbol.</param>
	/// <returns>A string containing the applicable accessors.</returns>
	private static string GetPropertyAccessors(IPropertySymbol propertySymbol)
	{
		string getter = propertySymbol.GetMethod != null && propertySymbol.GetMethod.DeclaredAccessibility == Accessibility.Public
			? "get; "
			: string.Empty;
		string setter = propertySymbol.SetMethod != null && propertySymbol.SetMethod.DeclaredAccessibility == Accessibility.Public
			? "set; "
			: string.Empty;
		return $" {getter}{setter}";
	}

	/// <summary>
	/// Generates an XML documentation comment that inherits documentation from the specified target property.
	/// </summary>
	/// <param name="request">The abstraction request containing the target type information for documentation inheritance.</param>
	/// <param name="propertySymbol">The symbol representing the property for which the documentation comment is generated.</param>
	/// <returns>
	/// A string containing the XML documentation comment that references the target property using <c>&lt;inheritdoc&gt;</c>.
	/// </returns>
	private static string CreatePropertyComment(AbstractionRequest request, IPropertySymbol propertySymbol)
		=> $"/// <inheritdoc cref=\"{request.TargetType}.{propertySymbol.Name}\"/>";

	/// <summary>
	/// Generates an XML documentation comment that inherits documentation from the specified target method.
	/// </summary>
	/// <param name="request">The abstraction request containing the target type information for documentation inheritance.</param>
	/// <param name="methodSymbol">The symbol representing the method for which the documentation comment is generated.</param>
	/// <returns>
	/// A string containing the XML documentation comment that references the target method using <c>&lt;inheritdoc&gt;</c>.
	/// </returns>
	private static string CreateMethodComment(AbstractionRequest request, IMethodSymbol methodSymbol)
	{
		IEnumerable<string> parameters = methodSymbol.Parameters.Select(p => $"{GetCrefParameterModifier(p)}{GetCrefTypeName(p.Type)}");
		return $"/// <inheritdoc cref=\"{request.TargetType}.{methodSymbol.Name}({string.Join(", ", parameters)})\"/>";
	}

	/// <summary>
	/// Gets the type name suitable for use in XML cref attributes, stripping nullable annotations
	/// and replacing angle brackets with curly braces.
	/// </summary>
	/// <param name="type">The type symbol.</param>
	/// <returns>A cref-safe type name string.</returns>
	private static string GetCrefTypeName(ITypeSymbol type)
		=> type.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
			.ToDisplayString()
			.Replace('<', '{')
			.Replace('>', '}');

	/// <summary>
	/// Gets the C# keyword prefix for a parameter in an XML cref attribute.
	/// Only <c>ref</c> and <c>out</c> are valid in cref attributes.
	/// </summary>
	/// <param name="parameter">The parameter symbol.</param>
	/// <returns>The modifier keyword followed by a space, or an empty string if none applies.</returns>
	private static string GetCrefParameterModifier(IParameterSymbol parameter)
	{
		return parameter.RefKind switch
		{
			RefKind.Out => "out ",
			RefKind.Ref => "ref ",
			_ => string.Empty
		};
	}

	/// <summary>
	/// Gets the C# keyword prefix for a parameter declaration based on its ref kind and params status.
	/// </summary>
	/// <param name="parameter">The parameter symbol.</param>
	/// <returns>The modifier keyword followed by a space, or an empty string if none applies.</returns>
	private static string GetParameterModifier(IParameterSymbol parameter)
	{
		return parameter.IsParams
			? "params "
			: parameter.RefKind switch
			{
				RefKind.Out => "out ",
				RefKind.Ref => "ref ",
				RefKind.In => "in ",
				_ => string.Empty
			};
	}

	/// <summary>
	/// Gets the C# keyword prefix for a call-site argument based on its ref kind.
	/// </summary>
	/// <param name="parameter">The parameter symbol.</param>
	/// <returns>The modifier keyword followed by a space, or an empty string if none applies.</returns>
	private static string GetCallSiteModifier(IParameterSymbol parameter)
	{
		return parameter.RefKind switch
		{
			RefKind.Out => "out ",
			RefKind.Ref => "ref ",
			_ => string.Empty
		};
	}

	/// <summary>
	/// Retrieves the fully qualified namespace of the specified type symbol.
	/// </summary>
	/// <remarks>
	/// This method excludes the global namespace from the result. Use this method to obtain
	/// the complete namespace path for code generation or analysis scenarios.
	/// </remarks>
	/// <param name="symbol">
	/// The <see cref="INamedTypeSymbol"/> representing the type whose namespace is to be obtained.
	/// </param>
	/// <returns>
	/// A string containing the full namespace of the type, with segments separated by periods.
	/// Returns an empty string if the type is declared in the global namespace.
	/// </returns>
	private static string GetFullNamespace(INamedTypeSymbol symbol)
	{
		var ns = symbol.ContainingNamespace;
		if (ns == null || ns.IsGlobalNamespace)
			return string.Empty;

		var parts = new List<string>();
		while (ns != null && !ns.IsGlobalNamespace)
		{
			parts.Insert(0, ns.Name);
			ns = ns.ContainingNamespace;
		}
		return string.Join(".", parts);
	}

	/// <summary>
	/// Creates an <see cref="AbstractionRequest"/> from the given syntax context if the class
	/// is decorated with the <see cref="GenerateAbstractionAttribute"/>.
	/// </summary>
	/// <param name="ctx">The syntax context.</param>
	/// <param name="ct">The cancellation token.</param>
	/// <returns>
	/// An <see cref="AbstractionRequest"/> if the class has the <see cref="GenerateAbstractionAttribute"/>;
	/// otherwise, <see langword="null"/>.
	/// </returns>
	private static AbstractionRequest? CreateAbstractionRequest(GeneratorSyntaxContext ctx, CancellationToken ct)
	{
		ClassDeclarationSyntax classDeclaration = (ClassDeclarationSyntax)ctx.Node;
		ISymbol? classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclaration, ct);
		if (classSymbol == null)
			return null;

		foreach (AttributeData attributeData in classSymbol.GetAttributes())
		{
			if (attributeData.AttributeClass?.ToDisplayString() == GeneratorAttributeName)
			{
				// Extract constructor arguments
				TypedConstant targetTypeArg = attributeData.ConstructorArguments[0];
				TypedConstant abstractionTypeArg = attributeData.ConstructorArguments[1];
				TypedConstant implementationTypeArg = attributeData.ConstructorArguments[2];
				TypedConstant excludeMethodsArg = attributeData.ConstructorArguments.Length > 3
					? attributeData.ConstructorArguments[3]
					: default;

				string[] excludeMethods = [];
				if (excludeMethodsArg.Kind is TypedConstantKind.Array)
					excludeMethods = [.. excludeMethodsArg.Values.Select(v => v.Value as string ?? string.Empty)];

				string[] excludeProperties = [];
				foreach (KeyValuePair<string, TypedConstant> namedArg in attributeData.NamedArguments)
				{
					if (namedArg.Key == nameof(GenerateAbstractionAttribute.ExcludeProperties) && namedArg.Value.Kind is TypedConstantKind.Array)
						excludeProperties = [.. namedArg.Value.Values.Select(v => v.Value as string ?? string.Empty)];
				}

				if (targetTypeArg.Value is INamedTypeSymbol targetType
					&& abstractionTypeArg.Value is INamedTypeSymbol abstractionType
					&& implementationTypeArg.Value is INamedTypeSymbol implementationType)
					return new AbstractionRequest(
						TargetType: targetType,
						AbstractionType: abstractionType,
						ImplementationType: implementationType,
						ExcludeMethods: excludeMethods,
						ExcludeProperties: excludeProperties
						);
			}
		}
		return null;
	}

	/// <summary>
	/// Indicates whether the given syntax node is a candidate for a class with the GenerateAbstraction attribute.
	/// </summary>
	/// <param name="node">The syntax node to check.</param>
	/// <returns>
	/// True if the node is a class declaration with the GenerateAbstraction attribute;
	/// otherwise, false.
	/// </returns>
	private static bool IsCandidateClassNode(SyntaxNode node)
		=> node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0;

	/// <summary>
	/// Converts an <see cref="Accessibility"/> value to its corresponding C# keyword.
	/// </summary>
	/// <param name="accessibility">The accessibility to convert.</param>
	/// <returns>The C# keyword string for the given accessibility.</returns>
	private static string GetAccessibilityKeyword(Accessibility accessibility) => accessibility switch
	{
		Accessibility.Public => "public",
		Accessibility.Internal => "internal",
		Accessibility.Protected => "protected",
		Accessibility.ProtectedOrInternal => "protected internal",
		Accessibility.ProtectedAndInternal => "private protected",
		Accessibility.Private => "private",
		_ => "public"
	};
}
