// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating compile-time constant properties for assembly information
/// on classes marked with the <see cref="GenerateAssemblyInformationAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AssemblyInformationGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(AssemblyInformationGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateAssemblyInformationAttribute).FullName;

	private static readonly (string AttributeName, string PropertyName)[] AssemblyAttributes =
	[
		("System.Reflection.AssemblyTitleAttribute", "Title"),
		("System.Reflection.AssemblyDescriptionAttribute", "Description"),
		("System.Reflection.AssemblyCompanyAttribute", "Company"),
		("System.Reflection.AssemblyProductAttribute", "Product"),
		("System.Reflection.AssemblyCopyrightAttribute", "Copyright"),
		("System.Reflection.AssemblyTrademarkAttribute", "Trademark"),
		("System.Reflection.AssemblyConfigurationAttribute", "Configuration"),
		("System.Reflection.AssemblyVersionAttribute", "Version"),
		("System.Reflection.AssemblyFileVersionAttribute", "FileVersion"),
		("System.Reflection.AssemblyInformationalVersionAttribute", "InformationalVersion"),
	];

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => Transform(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private static (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? Transform(GeneratorAttributeSyntaxContext context)
		=> context.TargetNode is not ClassDeclarationSyntax classSyntax ? null : ((ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?)(classSyntax, context.SemanticModel);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GetAccessibility(classDeclaration);

		Dictionary<string, string> assemblyValues = GetAssemblyAttributeValues(semanticModel.Compilation);

		List<(string Accessibility, string Name)> outerClasses = GetOuterClasses(classDeclaration);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in outerClasses)
		{
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{indent}{{");
			baseIndent++;
		}

		AppendPartialClass(sb, className, accessibility, assemblyValues, baseIndent);

		for (int i = outerClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}}}");
		}

		sb.AppendLine("}");

		string hintName = outerClasses.Count > 0
			? $"{string.Join(".", outerClasses.Select(o => o.Name))}.{className}.AssemblyInformation.g.cs"
			: $"{className}.AssemblyInformation.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, Dictionary<string, string> assemblyValues, int indentLevel = 1)
	{
		string indent = new(' ', indentLevel * 2);
		string innerIndent = new(' ', (indentLevel + 1) * 2);

		sb.AppendLine($"{indent}{accessibility} partial class {className}");
		sb.AppendLine($"{indent}{{");

		bool first = true;
		foreach ((string attributeName, string propertyName) in AssemblyAttributes)
		{
			if (!first)
				sb.AppendLine();

			first = false;

			string value = assemblyValues.TryGetValue(attributeName, out string? v) ? v : string.Empty;
			string escaped = value.Replace("\\", "\\\\").Replace("\"", "\\\"");

			sb.AppendLine($"{innerIndent}/// <summary>");
			sb.AppendLine($"{innerIndent}/// Gets the assembly {propertyName.ToLowerInvariant()} information.");
			sb.AppendLine($"{innerIndent}/// </summary>");
			sb.AppendLine($"{innerIndent}public const string {propertyName} = \"{escaped}\";");
		}

		sb.AppendLine($"{indent}}}");
	}

	private static Dictionary<string, string> GetAssemblyAttributeValues(Compilation compilation)
	{
		Dictionary<string, string> values = new(StringComparer.Ordinal);

		foreach (AttributeData attribute in compilation.Assembly.GetAttributes())
		{
			string? fullName = attribute.AttributeClass?.ToDisplayString();
			if (fullName is null)
				continue;

			if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string strValue)
				values[fullName] = strValue;
		}

		return values;
	}

	private static string GetAccessibility(ClassDeclarationSyntax classDeclaration)
	{
		foreach (SyntaxToken modifier in classDeclaration.Modifiers)
		{
			if (modifier.IsKind(SyntaxKind.PublicKeyword))
				return "public";
			if (modifier.IsKind(SyntaxKind.InternalKeyword))
				return "internal";
		}

		return "internal";
	}

	private static List<(string Accessibility, string Name)> GetOuterClasses(ClassDeclarationSyntax classDeclaration)
	{
		List<(string Accessibility, string Name)> outerClasses = [];
		SyntaxNode? parent = classDeclaration.Parent;

		while (parent is ClassDeclarationSyntax outerClass)
		{
			outerClasses.Add((GetAccessibility(outerClass), outerClass.Identifier.Text));
			parent = outerClass.Parent;
		}

		outerClasses.Reverse();
		return outerClasses;
	}
}
