// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a fluent builder class for classes marked
/// with the <see cref="GenerateBuilderAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BuilderGenerator : IIncrementalGenerator
{
  private static readonly string GeneratorName = typeof(BuilderGenerator).FullName;
  private static readonly string GeneratorAttributeName = typeof(GenerateBuilderAttribute).FullName;

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
      context.SyntaxProvider
        .ForAttributeWithMetadataName(
          fullyQualifiedMetadataName: GeneratorAttributeName,
          predicate: static (node, _) => node is ClassDeclarationSyntax,
          transform: static (ctx, _) => Transform(ctx))
        .Where(static result => result is not null);

    context.RegisterSourceOutput(provider, Execute);
  }

  private static (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? Transform(GeneratorAttributeSyntaxContext context)
  {
    if (context.TargetNode is not ClassDeclarationSyntax classSyntax)
      return null;

    return (classSyntax, context.SemanticModel);
  }

  private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
  {
    if (input is null)
      return;

    ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
    SemanticModel semanticModel = input.Value.SemanticModel;

    INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
    if (classSymbol is null)
      return;

    string className = classSymbol.Name;
    string namespaceName = classDeclaration.GetNamespace();
    string accessibility = GetAccessibility(classDeclaration);
    string builderClassName = $"{className}Builder";

    ImmutableArray<PropertyInfo> properties = GetSettableProperties(classSymbol);

    if (properties.Length == 0)
      return;

    StringBuilder sb = new();

    sb.AppendAutoGeneratedWarning(GeneratorName);
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine($"namespace {namespaceName}");
    sb.AppendLine("{");

    AppendBuilderClass(sb, className, builderClassName, accessibility, properties);

    sb.AppendLine("}");

    context.AddSource($"{builderClassName}.g.cs", sb.ToString());
  }

  private static void AppendBuilderClass(StringBuilder sb, string className, string builderClassName, string accessibility, ImmutableArray<PropertyInfo> properties)
  {
    sb.AppendLine($"  /// <summary>");
    sb.AppendLine($"  /// A fluent builder for creating instances of <see cref=\"{className}\"/>.");
    sb.AppendLine($"  /// </summary>");
    sb.AppendLine($"  {accessibility} sealed class {builderClassName}");
    sb.AppendLine("  {");

    // Fields
    foreach (PropertyInfo prop in properties)
    {
      string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name.Substring(1)}";
      string typeName = prop.IsReferenceType && prop.IsNullable ? $"{prop.TypeName}?" : prop.TypeName;
      string initializer = prop.IsReferenceType && !prop.IsNullable ? " = default!;" : ";";
      sb.AppendLine($"    private {typeName} {fieldName}{initializer}");
    }

    sb.AppendLine();

    // With methods
    foreach (PropertyInfo prop in properties)
    {
      string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name.Substring(1)}";
      string typeName = prop.IsReferenceType && prop.IsNullable ? $"{prop.TypeName}?" : prop.TypeName;
      sb.AppendLine($"    /// <summary>");
      sb.AppendLine($"    /// Sets the value for the <see cref=\"{className}.{prop.Name}\"/> property.");
      sb.AppendLine($"    /// </summary>");
      sb.AppendLine($"    /// <param name=\"value\">The value to set.</param>");
      sb.AppendLine($"    /// <returns>The current builder instance.</returns>");
      sb.AppendLine($"    public {builderClassName} With{prop.Name}({typeName} value)");
      sb.AppendLine("    {");
      sb.AppendLine($"      {fieldName} = value;");
      sb.AppendLine($"      return this;");
      sb.AppendLine("    }");
      sb.AppendLine();
    }

    // Build method
    sb.AppendLine($"    /// <summary>");
    sb.AppendLine($"    /// Creates a new instance of <see cref=\"{className}\"/> with the configured property values.");
    sb.AppendLine($"    /// </summary>");
    sb.AppendLine($"    /// <returns>A new <see cref=\"{className}\"/> instance.</returns>");
    sb.AppendLine($"    public {className} Build()");
    sb.AppendLine("    {");
    sb.AppendLine($"      return new {className}()");
    sb.AppendLine("      {");

    for (int i = 0; i < properties.Length; i++)
    {
      PropertyInfo prop = properties[i];
      string fieldName = $"_{char.ToLowerInvariant(prop.Name[0])}{prop.Name.Substring(1)}";
      string separator = i < properties.Length - 1 ? "," : string.Empty;
      sb.AppendLine($"        {prop.Name} = {fieldName}{separator}");
    }

    sb.AppendLine("      };");
    sb.AppendLine("    }");

    sb.AppendLine("  }");
  }

  private static ImmutableArray<PropertyInfo> GetSettableProperties(INamedTypeSymbol classSymbol)
  {
    ImmutableArray<PropertyInfo>.Builder builder = ImmutableArray.CreateBuilder<PropertyInfo>();

    foreach (ISymbol member in classSymbol.GetMembers())
    {
      if (member is not IPropertySymbol propertySymbol)
        continue;

      if (propertySymbol.DeclaredAccessibility != Accessibility.Public)
        continue;

      if (propertySymbol.IsReadOnly || propertySymbol.IsStatic || propertySymbol.SetMethod is null)
        continue;

      if (propertySymbol.SetMethod.DeclaredAccessibility != Accessibility.Public)
        continue;

      bool isReferenceType = propertySymbol.Type.IsReferenceType;
      bool isNullable = propertySymbol.NullableAnnotation == NullableAnnotation.Annotated;

      builder.Add(new PropertyInfo(propertySymbol.Name, propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), isReferenceType, isNullable));
    }

    return builder.ToImmutable();
  }

  private static string GetAccessibility(ClassDeclarationSyntax classDeclaration)
  {
    foreach (SyntaxToken modifier in classDeclaration.Modifiers)
    {
      if (modifier.IsKind(SyntaxKind.PublicKeyword))
        return "public";
      if (modifier.IsKind(SyntaxKind.InternalKeyword))
        return "internal";
    }

    return "internal";
  }

  private readonly struct PropertyInfo
  {
    public PropertyInfo(string name, string typeName, bool isReferenceType, bool isNullable)
    {
      Name = name;
      TypeName = typeName;
      IsReferenceType = isReferenceType;
      IsNullable = isNullable;
    }

    public string Name { get; }
    public string TypeName { get; }
    public bool IsReferenceType { get; }
    public bool IsNullable { get; }
  }
}
