// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating clone methods for classes marked
/// with the <see cref="GenerateCloneableAttribute"/> attribute. The generated code includes
/// a <c>Clone()</c> method for shallow copying and a <c>DeepClone()</c> method that
/// recursively deep clones reference-type properties also marked with
/// <see cref="GenerateCloneableAttribute"/>, implementing <c>ICloneable</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CloneableGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(CloneableGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateCloneableAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => Transform(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private static (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? Transform(GeneratorAttributeSyntaxContext context)
		=> context.TargetNode is not ClassDeclarationSyntax classSyntax ? null : ((ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?)(classSyntax, context.SemanticModel);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GetAccessibility(classDeclaration);

		HashSet<string> excludedProperties = GetExcludedProperties(classDeclaration, semanticModel);
		ImmutableArray<PropertyInfo> properties = GetPublicProperties(classSymbol, excludedProperties);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		AppendPartialClass(sb, className, accessibility, properties);

		sb.AppendLine("}");

		context.AddSource($"{className}.Cloneable.g.cs", sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<PropertyInfo> properties)
	{
		sb.AppendLine($"  {accessibility} partial class {className} : System.ICloneable");
		sb.AppendLine("  {");

		AppendCloneMethod(sb, className, properties);
		sb.AppendLine();
		AppendDeepCloneMethod(sb, className, properties);
		sb.AppendLine();
		AppendICloneableClone(sb);

		sb.AppendLine("  }");
	}

	private static void AppendCloneMethod(StringBuilder sb, string className, ImmutableArray<PropertyInfo> properties)
	{
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Creates a shallow copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    /// <returns>A new <see cref=\"{className}\"/> instance with the same property values.</returns>");
		sb.AppendLine($"    public {className} Clone()");
		sb.AppendLine("    {");
		sb.AppendLine($"      {className} clone = new {className}();");

		foreach (PropertyInfo property in properties)
			sb.AppendLine($"      clone.{property.Name} = this.{property.Name};");

		sb.AppendLine("      return clone;");
		sb.AppendLine("    }");
	}

	private static void AppendDeepCloneMethod(StringBuilder sb, string className, ImmutableArray<PropertyInfo> properties)
	{
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Creates a deep copy of this <see cref=\"{className}\"/> instance.");
		sb.AppendLine("    /// Reference-type properties marked with <c>[GenerateCloneable]</c> are recursively deep cloned.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    /// <returns>A new <see cref=\"{className}\"/> instance with deeply cloned property values.</returns>");
		sb.AppendLine($"    public {className} DeepClone()");
		sb.AppendLine("    {");
		sb.AppendLine($"      {className} clone = new {className}();");

		foreach (PropertyInfo property in properties)
		{
			if (property.IsCloneable)
			{
				sb.AppendLine($"      clone.{property.Name} = this.{property.Name}?.DeepClone();");
			}
			else
			{
				sb.AppendLine($"      clone.{property.Name} = this.{property.Name};");
			}
		}

		sb.AppendLine("      return clone;");
		sb.AppendLine("    }");
	}

	private static void AppendICloneableClone(StringBuilder sb)
	{
		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine($"    object System.ICloneable.Clone()");
		sb.AppendLine("      => DeepClone();");
	}

	private static ImmutableArray<PropertyInfo> GetPublicProperties(INamedTypeSymbol classSymbol, HashSet<string> excludedProperties)
	{
		ImmutableArray<PropertyInfo>.Builder builder = ImmutableArray.CreateBuilder<PropertyInfo>();

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			if (propertySymbol.DeclaredAccessibility != Accessibility.Public)
				continue;

			if (propertySymbol.IsStatic || propertySymbol.IsReadOnly || propertySymbol.IsWriteOnly)
				continue;

			if (propertySymbol.GetMethod is null || propertySymbol.SetMethod is null)
				continue;

			if (excludedProperties.Contains(propertySymbol.Name))
				continue;

			bool isCloneable = HasGenerateCloneableAttribute(propertySymbol.Type);

			builder.Add(new PropertyInfo(propertySymbol.Name, isCloneable));
		}

		return builder.ToImmutable();
	}

	private static bool HasGenerateCloneableAttribute(ITypeSymbol typeSymbol)
	{
		foreach (AttributeData attr in typeSymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == GeneratorAttributeName)
				return true;
		}

		return false;
	}

	private static HashSet<string> GetExcludedProperties(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		HashSet<string> excluded = new(StringComparer.Ordinal);

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not "GenerateCloneable" and not "GenerateCloneableAttribute")
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					Optional<object?> constantValue = semanticModel.GetConstantValue(argument.Expression);

					if (constantValue.HasValue && constantValue.Value is string value)
						excluded.Add(value);
				}
			}
		}

		return excluded;
	}

	private static string GetAccessibility(ClassDeclarationSyntax classDeclaration)
	{
		foreach (SyntaxToken modifier in classDeclaration.Modifiers)
		{
			if (modifier.IsKind(SyntaxKind.PublicKeyword))
				return "public";
			if (modifier.IsKind(SyntaxKind.InternalKeyword))
				return "internal";
		}

		return "internal";
	}

	private readonly struct PropertyInfo(string name, bool isCloneable)
	{
		public string Name { get; } = name;
		public bool IsCloneable { get; } = isCloneable;
	}
}
