// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating the decorator pattern for classes marked
/// with the <see cref="GenerateDecoratorAttribute"/> attribute. The generated code
/// wraps an inner instance, delegates all interface members, and exposes them as
/// virtual methods for selective overriding.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DecoratorGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(DecoratorGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateDecoratorAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
			return;

		ImmutableArray<INamedTypeSymbol> interfaces = classSymbol.Interfaces;
		if (interfaces.Length == 0)
		{
			Diagnostic diagnostic = Diagnostic.Create(
				DiagnosticDescriptors.DecoratorRequiresInterfaceDiagnostic,
				classDeclaration.Identifier.GetLocation(),
				classSymbol.Name);
			context.ReportDiagnostic(diagnostic);
			return;
		}

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);

		// Collect all interface members across all implemented interfaces (including inherited)
		List<InterfaceInfo> interfaceInfos = [];
		foreach (INamedTypeSymbol interfaceSymbol in GetAllInterfaces(interfaces))
			interfaceInfos.Add(new InterfaceInfo(interfaceSymbol));

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		AppendPartialClass(sb, className, accessibility, interfaces, interfaceInfos);

		sb.AppendLine("}");

		context.AddSource($"{className}.Decorator.g.cs", sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<INamedTypeSymbol> directInterfaces, List<InterfaceInfo> interfaceInfos)
	{
		// Use the first direct interface as the inner field type
		INamedTypeSymbol primaryInterface = directInterfaces[0];
		string innerTypeName = primaryInterface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

		sb.AppendLine($"  {accessibility} partial class {className}");
		sb.AppendLine("  {");

		// Inner field
		sb.AppendLine($"    private readonly {innerTypeName} _inner;");
		sb.AppendLine();

		// Constructor
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Initializes a new instance of the <see cref=\"{className}\"/> class,");
		sb.AppendLine($"    /// wrapping the specified <paramref name=\"inner\"/> instance.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    /// <param name=\"inner\">The inner <see cref=\"{innerTypeName}\"/> instance to decorate.</param>");
		sb.AppendLine($"    public {className}({innerTypeName} inner)");
		sb.AppendLine("    {");
		sb.AppendLine("      _inner = inner ?? throw new System.ArgumentNullException(nameof(inner));");
		sb.AppendLine("    }");

		// Collect all interfaces that the primary interface already covers (itself + its full hierarchy)
		HashSet<string> primaryCovers = new(StringComparer.Ordinal)
		{
			primaryInterface.ToDisplayString()
		};
		foreach (INamedTypeSymbol inherited in primaryInterface.AllInterfaces)
			primaryCovers.Add(inherited.ToDisplayString());

		// Generate members for all interfaces
		foreach (InterfaceInfo info in interfaceInfos)
		{
			// Determine the inner accessor expression - cast if the interface is not covered by the primary interface type
			string innerAccess = primaryCovers.Contains(info.InterfaceSymbol.ToDisplayString())
				? "_inner"
				: $"(({info.InterfaceSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)})_inner)";

			foreach (IMethodSymbol method in info.Methods)
			{
				sb.AppendLine();
				AppendMethodDelegation(sb, method, innerAccess);
			}

			foreach (IPropertySymbol property in info.Properties)
			{
				sb.AppendLine();
				AppendPropertyDelegation(sb, property, innerAccess);
			}

			foreach (IEventSymbol evt in info.Events)
			{
				sb.AppendLine();
				AppendEventDelegation(sb, evt, innerAccess);
			}
		}

		sb.AppendLine("  }");
	}

	private static void AppendMethodDelegation(StringBuilder sb, IMethodSymbol method, string innerAccess)
	{
		string returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
		string methodName = method.Name;
		string parameters = GetParameterList(method);
		string arguments = GetArgumentList(method);

		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine($"    public virtual {returnType} {methodName}({parameters})");
		sb.AppendLine($"      => {innerAccess}.{methodName}({arguments});");
	}

	private static void AppendPropertyDelegation(StringBuilder sb, IPropertySymbol property, string innerAccess)
	{
		string propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
		string propertyName = property.Name;

		bool hasGetter = property.GetMethod is not null && property.GetMethod.DeclaredAccessibility == Accessibility.Public;
		bool hasSetter = property.SetMethod is not null && property.SetMethod.DeclaredAccessibility == Accessibility.Public;

		sb.AppendLine("    /// <inheritdoc/>");

		if (hasGetter && hasSetter)
		{
			sb.AppendLine($"    public virtual {propertyType} {propertyName}");
			sb.AppendLine("    {");
			sb.AppendLine($"      get => {innerAccess}.{propertyName};");
			sb.AppendLine($"      set => {innerAccess}.{propertyName} = value;");
			sb.AppendLine("    }");
		}
		else if (hasGetter)
		{
			sb.AppendLine($"    public virtual {propertyType} {propertyName}");
			sb.AppendLine($"      => {innerAccess}.{propertyName};");
		}
		else if (hasSetter)
		{
			sb.AppendLine($"    public virtual {propertyType} {propertyName}");
			sb.AppendLine("    {");
			sb.AppendLine($"      set => {innerAccess}.{propertyName} = value;");
			sb.AppendLine("    }");
		}
	}

	private static void AppendEventDelegation(StringBuilder sb, IEventSymbol evt, string innerAccess)
	{
		string eventType = evt.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
		string eventName = evt.Name;

		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine($"    public virtual event {eventType} {eventName}");
		sb.AppendLine("    {");
		sb.AppendLine($"      add => {innerAccess}.{eventName} += value;");
		sb.AppendLine($"      remove => {innerAccess}.{eventName} -= value;");
		sb.AppendLine("    }");
	}

	private static string GetParameterList(IMethodSymbol method)
	{
		List<string> parts = [];
		foreach (IParameterSymbol param in method.Parameters)
		{
			string modifier = param.RefKind switch
			{
				RefKind.Ref => "ref ",
				RefKind.Out => "out ",
				RefKind.In => "in ",
				RefKind.RefReadOnlyParameter => "ref readonly ",
				_ => string.Empty
			};

			string typeName = param.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
			parts.Add($"{modifier}{typeName} {param.Name}");
		}

		return string.Join(", ", parts);
	}

	private static string GetArgumentList(IMethodSymbol method)
	{
		List<string> parts = [];
		foreach (IParameterSymbol param in method.Parameters)
		{
			string modifier = param.RefKind switch
			{
				RefKind.Ref => "ref ",
				RefKind.Out => "out ",
				RefKind.In => "in ",
				_ => string.Empty
			};

			parts.Add($"{modifier}{param.Name}");
		}

		return string.Join(", ", parts);
	}

	/// <summary>
	/// Gets all interfaces from the direct interfaces list, including any inherited interfaces,
	/// in a deduplicated, depth-first order.
	/// </summary>
	private static List<INamedTypeSymbol> GetAllInterfaces(ImmutableArray<INamedTypeSymbol> directInterfaces)
	{
		HashSet<string> seen = new(StringComparer.Ordinal);
		List<INamedTypeSymbol> result = [];

		foreach (INamedTypeSymbol iface in directInterfaces)
		{
			CollectInterfaces(iface, seen, result);
		}

		return result;
	}

	private static void CollectInterfaces(INamedTypeSymbol iface, HashSet<string> seen, List<INamedTypeSymbol> result)
	{
		string key = iface.ToDisplayString();
		if (!seen.Add(key))
			return;

		// Collect base interfaces first
		foreach (INamedTypeSymbol baseInterface in iface.Interfaces)
		{
			CollectInterfaces(baseInterface, seen, result);
		}

		result.Add(iface);
	}

	private sealed class InterfaceInfo
	{
		public INamedTypeSymbol InterfaceSymbol { get; }
		public List<IMethodSymbol> Methods { get; } = [];
		public List<IPropertySymbol> Properties { get; } = [];
		public List<IEventSymbol> Events { get; } = [];

		public InterfaceInfo(INamedTypeSymbol interfaceSymbol)
		{
			InterfaceSymbol = interfaceSymbol;
			foreach (ISymbol member in interfaceSymbol.GetMembers())
			{
				switch (member)
				{
					case IMethodSymbol method when method.MethodKind == MethodKind.Ordinary:
						Methods.Add(method);
						break;
					case IPropertySymbol property:
						Properties.Add(property);
						break;
					case IEventSymbol evt:
						Events.Add(evt);
						break;
				}
			}
		}
	}
}
