// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating enumerator extensions for enumerators marked
/// with the <see cref="GenerateEnumeratorExtensionsAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EnumeratorExtensionsGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(EnumeratorExtensionsGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateEnumeratorExtensionsAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(EnumDeclarationSyntax EnumDeclaration, SemanticModel SemanticModel)> provider = context.SyntaxProvider
			 .ForAttributeWithMetadataName(
				 fullyQualifiedMetadataName: GeneratorAttributeName,
				 predicate: (node, _) => Predicate(node),
				transform: (context, _) => Transform(context));

		context.RegisterSourceOutput(provider, Execute);
	}

	/// <inheritdoc/>
	private void Execute(SourceProductionContext context, (EnumDeclarationSyntax EnumDeclaration, SemanticModel SemanticModel) data)
	{
		EnumDeclarationSyntax enumDeclaration = data.EnumDeclaration;

		ImmutableArray<EnumMemberDeclarationSyntax> members = [.. enumDeclaration.Members
				.OfType<EnumMemberDeclarationSyntax>()
				.Where(field => field is not null)];

		if (!members.Any())
			return;

		string enumName = enumDeclaration.Identifier.Text;
		string enumNamespace = enumDeclaration.GetNamespace() ?? "GlobalNamespace";

		StringBuilder sourceBuilder = new();

		sourceBuilder.AppendAutoGeneratedWarning(GeneratorName);
		AppendHeader(sourceBuilder);
		AppendNamespaceStart(sourceBuilder, enumNamespace);
		AppendClassStart(sourceBuilder, enumName);

		AppendToStringFast(sourceBuilder, enumName, members);
		AppendIsDefinedFast(sourceBuilder, enumName, members);
		AppendGetDescriptionFast(sourceBuilder, enumName, members, data.SemanticModel);
		AppendGetNamesFast(sourceBuilder, enumName, members);
		AppendGetValuesFast(sourceBuilder, enumName, members);

		AppendClassEnd(sourceBuilder);
		AppendNamespaceEnd(sourceBuilder);

		context.AddSource($"{enumName}.g.cs", sourceBuilder.ToString());
	}

	/// <inheritdoc/>
	private static (EnumDeclarationSyntax EnumDeclaration, SemanticModel SemanticModel) Transform(GeneratorAttributeSyntaxContext context)
		=> ((EnumDeclarationSyntax)context.TargetNode, context.SemanticModel);

	/// <inheritdoc/>
	private static bool Predicate(SyntaxNode node)
		=> node is EnumDeclarationSyntax;

	private static void AppendHeader(StringBuilder builder)
	{
		builder.AppendLine("using System;");
		builder.AppendLine("using System.ComponentModel;");
		builder.AppendLine();
	}

	private static void AppendNamespaceStart(StringBuilder builder, string namespaceName)
	{
		builder.AppendLine($"namespace {namespaceName}");
		builder.AppendLine("{");
	}

	private static void AppendClassStart(StringBuilder builder, string enumName)
	{
		builder.AppendLine("  /// <summary>");
		builder.AppendLine($"  /// The <see cref=\"{enumName}Extensions\"/> class provides extension methods for the <see cref=\"{enumName}\"/> enumeration.");
		builder.AppendLine("  /// </summary>");
		builder.AppendLine($"  public static class {enumName}Extensions");
		builder.AppendLine("  {");
	}

	private static void AppendClassEnd(StringBuilder builder)
	{
		builder.AppendLine("  }");
	}

	private static void AppendNamespaceEnd(StringBuilder builder)
	{
		builder.AppendLine("}");
	}

	private static void AppendToStringFast(StringBuilder builder, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		builder.AppendLine("    /// <summary>");
		builder.AppendLine("    /// Returns the name of the enumeration <paramref name=\"value\"/> as a string.");
		builder.AppendLine("    /// </summary>");
		builder.AppendLine("    /// <param name=\"value\">The enumeration value to convert to a string.</param>");
		builder.AppendLine("    /// <returns>The name of the enumeration value as a string.</returns>");
		builder.AppendLine($"    public static string ToStringFast(this {enumName} value)");
		builder.AppendLine("    {");
		builder.AppendLine("      return value switch");
		builder.AppendLine("      {");
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			builder.AppendLine($"        {enumName}.{memberName} => nameof({enumName}.{memberName}),");
		}
		builder.AppendLine("        _ => value.ToString()");
		builder.AppendLine("      };");
		builder.AppendLine("    }");
		builder.AppendLine();
	}

	private static void AppendIsDefinedFast(StringBuilder builder, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		builder.AppendLine("    /// <summary>");
		builder.AppendLine("    /// Returns whether the specified enumeration <paramref name=\"value\"/> is defined");
		builder.AppendLine($"    /// in the <see cref=\"{enumName}\"/>.");
		builder.AppendLine("    /// </summary>");
		builder.AppendLine("    /// <param name=\"value\">The enumeration value to check.</param>");
		builder.AppendLine("    /// <returns>True if the enumeration value is defined; otherwise, false.</returns>");
		builder.AppendLine($"    public static bool IsDefinedFast(this {enumName} value)");
		builder.AppendLine("    {");
		builder.AppendLine("      return value switch");
		builder.AppendLine("      {");
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			builder.AppendLine($"        {enumName}.{memberName} => true,");
		}
		builder.AppendLine("        _ => false");
		builder.AppendLine("      };");
		builder.AppendLine("    }");
		builder.AppendLine();
		builder.AppendLine("    /// <summary>");
		builder.AppendLine("    /// Returns whether the specified enumeration <paramref name=\"name\"/> is defined");
		builder.AppendLine($"    /// in the <see cref=\"{enumName}\"/>.");
		builder.AppendLine("    /// </summary>");
		builder.AppendLine("    /// <param name=\"name\">The name of the enumeration value to check.</param>");
		builder.AppendLine("    /// <returns>True if the enumeration value is defined; otherwise, false.</returns>");
		builder.AppendLine($"    public static bool IsDefinedFast(this string name)");
		builder.AppendLine("    {");
		builder.AppendLine("      return name switch");
		builder.AppendLine("      {");
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			builder.AppendLine($"        nameof({enumName}.{memberName}) => true,");
		}
		builder.AppendLine("        _ => false");
		builder.AppendLine("      };");
		builder.AppendLine("    }");
		builder.AppendLine();
	}

	private static void AppendGetNamesFast(StringBuilder builder, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		builder.AppendLine("    /// <summary>");
		builder.AppendLine($"    /// Returns the names of the <see cref=\"{enumName}\"/> enumeration as an collection of strings.");
		builder.AppendLine("    /// </summary>");
		builder.AppendLine("    /// <param name=\"value\">The enumeration value to get the names for.</param>");
		builder.AppendLine("    /// <returns>An array of strings containing the names of the enumeration values.</returns>");
		builder.AppendLine($"    public static IEnumerable<string> GetNamesFast(this {enumName} value)");
		builder.AppendLine("    {");
		builder.AppendLine("      return new[]");
		builder.AppendLine("      {");
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			builder.AppendLine($"        nameof({enumName}.{memberName}),");
		}
		builder.AppendLine("      };");
		builder.AppendLine("    }");
		builder.AppendLine();
	}

	private static void AppendGetValuesFast(StringBuilder builder, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members)
	{
		builder.AppendLine("    /// <summary>");
		builder.AppendLine($"    /// Returns the values of the <see cref=\"{enumName}\"/> enumeration.");
		builder.AppendLine("    /// </summary>");
		builder.AppendLine("    /// <param name=\"value\">The enumeration value to get the values for.</param>");
		builder.AppendLine("    /// <returns>An collection of the enumeration values.</returns>");
		builder.AppendLine($"    public static IEnumerable<{enumName}> GetValuesFast(this {enumName} value)");
		builder.AppendLine("    {");
		builder.AppendLine("      return new[]");
		builder.AppendLine("      {");
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			builder.AppendLine($"        {enumName}.{memberName},");
		}
		builder.AppendLine("      };");
		builder.AppendLine("    }");
		builder.AppendLine();
	}

	private static void AppendGetDescriptionFast(StringBuilder builder, string enumName, ImmutableArray<EnumMemberDeclarationSyntax> members, SemanticModel semanticModel)
	{
		builder.AppendLine("    /// <summary>");
		builder.AppendLine($"    /// Returns the description of the <see cref=\"{enumName}\"/> enumeration if the");
		builder.AppendLine("    /// <see cref=\"System.ComponentModel.DescriptionAttribute\"/> is applied to the");
		builder.AppendLine("    /// enumeration value; otherwise, returns the name of the enumeration value.");
		builder.AppendLine("    /// </summary>");
		builder.AppendLine("    /// <param name=\"value\">The enumeration value to get the description for.</param>");
		builder.AppendLine("    /// <returns>The description of the enumeration value, or its name if no description is set.</returns>");
		builder.AppendLine($"    public static string GetDescriptionFast(this {enumName} value)");
		builder.AppendLine("    {");
		builder.AppendLine("      return value switch");
		builder.AppendLine("      {");
		foreach (EnumMemberDeclarationSyntax member in members)
		{
			string memberName = member.Identifier.Text;
			string? description = GetDescriptionFromAttributes(member, semanticModel);

			if (description is not null)
				builder.AppendLine($"        {enumName}.{memberName} => \"{description}\",");
			else
				builder.AppendLine($"        {enumName}.{memberName} => nameof({enumName}.{memberName}),");
		}
		builder.AppendLine("        _ => value.ToString()");
		builder.AppendLine("      };");
		builder.AppendLine("    }");
		builder.AppendLine();
	}

	private static string? GetDescriptionFromAttributes(EnumMemberDeclarationSyntax member, SemanticModel semanticModel)
	{
		INamedTypeSymbol? descriptionAttributeSymbol = semanticModel.Compilation.GetTypeByMetadataName("System.ComponentModel.DescriptionAttribute");

		if (descriptionAttributeSymbol is null)
			return null;

		foreach (AttributeListSyntax attributeList in member.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				SymbolInfo symbolInfo = semanticModel.GetSymbolInfo(attribute);
				if (symbolInfo.Symbol is not IMethodSymbol attributeConstructor)
					continue;

				if (!SymbolEqualityComparer.Default.Equals(attributeConstructor.ContainingType, descriptionAttributeSymbol))
					continue;

				if (attribute.ArgumentList?.Arguments.Count > 0)
				{
					AttributeArgumentSyntax argument = attribute.ArgumentList.Arguments[0];
					Optional<object?> descriptionValue = semanticModel.GetConstantValue(argument.Expression);

					if (descriptionValue.HasValue && descriptionValue.Value is string description)
						return description;

					return argument.ToString().Trim('"');
				}
			}
		}

		return null;
	}
}
