// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating equality members for classes marked
/// with the <see cref="GenerateEqualityAttribute"/> attribute. The generated code includes
/// <c>Equals(object)</c>, <c>Equals(T)</c>, <c>GetHashCode()</c>,
/// <c>operator ==</c>, and <c>operator !=</c>, implementing <c>IEquatable&lt;T&gt;</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EqualityGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(EqualityGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateEqualityAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => Transform(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private static (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? Transform(GeneratorAttributeSyntaxContext context)
		=> context.TargetNode is not ClassDeclarationSyntax classSyntax ? null : ((ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?)(classSyntax, context.SemanticModel);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GetAccessibility(classDeclaration);

		HashSet<string> excludedProperties = GetExcludedProperties(classDeclaration);
		ImmutableArray<PropertyInfo> properties = GetPublicProperties(classSymbol, excludedProperties);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		AppendPartialClass(sb, className, accessibility, properties);

		sb.AppendLine("}");

		context.AddSource($"{className}.Equality.g.cs", sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<PropertyInfo> properties)
	{
		sb.AppendLine($"  {accessibility} partial class {className} : System.IEquatable<{className}>");
		sb.AppendLine("  {");

		AppendEqualsObject(sb, className);
		sb.AppendLine();
		AppendEqualsT(sb, className, properties);
		sb.AppendLine();
		AppendGetHashCode(sb, properties);
		sb.AppendLine();
		AppendOperatorEquals(sb, className);
		sb.AppendLine();
		AppendOperatorNotEquals(sb, className);

		sb.AppendLine("  }");
	}

	private static void AppendEqualsObject(StringBuilder sb, string className)
	{
		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine("    public override bool Equals(object? obj)");
		sb.AppendLine($"      => Equals(obj as {className});");
	}

	private static void AppendEqualsT(StringBuilder sb, string className, ImmutableArray<PropertyInfo> properties)
	{
		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine($"    public bool Equals({className}? other)");
		sb.AppendLine("    {");
		sb.AppendLine("      if (other is null)");
		sb.AppendLine("        return false;");
		sb.AppendLine();
		sb.AppendLine("      if (ReferenceEquals(this, other))");
		sb.AppendLine("        return true;");

		if (properties.Length > 0)
		{
			sb.AppendLine();
			sb.Append("      return ");

			for (int i = 0; i < properties.Length; i++)
			{
				if (i > 0)
				{
					sb.AppendLine();
					sb.Append("        && ");
				}

				sb.Append($"Equals({properties[i].Name}, other.{properties[i].Name})");
			}

			sb.AppendLine(";");
		}
		else
		{
			sb.AppendLine();
			sb.AppendLine("      return true;");
		}

		sb.AppendLine("    }");
	}

	private static void AppendGetHashCode(StringBuilder sb, ImmutableArray<PropertyInfo> properties)
	{
		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine("    public override int GetHashCode()");
		sb.AppendLine("    {");

		if (properties.Length == 0)
		{
			sb.AppendLine("      return base.GetHashCode();");
		}
		else
		{
			sb.AppendLine("      unchecked");
			sb.AppendLine("      {");
			sb.AppendLine("        int hash = 17;");

			foreach (PropertyInfo property in properties)
			{
				if (property.IsValueType)
					sb.AppendLine($"        hash = hash * 31 + {property.Name}.GetHashCode();");
				else
					sb.AppendLine($"        hash = hash * 31 + ({property.Name}?.GetHashCode() ?? 0);");
			}

			sb.AppendLine("        return hash;");
			sb.AppendLine("      }");
		}

		sb.AppendLine("    }");
	}

	private static void AppendOperatorEquals(StringBuilder sb, string className)
	{
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Determines whether two <see cref=\"{className}\"/> instances are equal.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    public static bool operator ==({className}? left, {className}? right)");
		sb.AppendLine("      => Equals(left, right);");
	}

	private static void AppendOperatorNotEquals(StringBuilder sb, string className)
	{
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Determines whether two <see cref=\"{className}\"/> instances are not equal.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    public static bool operator !=({className}? left, {className}? right)");
		sb.AppendLine("      => !Equals(left, right);");
	}

	private static ImmutableArray<PropertyInfo> GetPublicProperties(INamedTypeSymbol classSymbol, HashSet<string> excludedProperties)
	{
		ImmutableArray<PropertyInfo>.Builder builder = ImmutableArray.CreateBuilder<PropertyInfo>();

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			if (propertySymbol.DeclaredAccessibility != Accessibility.Public)
				continue;

			if (propertySymbol.IsStatic || propertySymbol.IsWriteOnly || propertySymbol.GetMethod is null)
				continue;

			if (excludedProperties.Contains(propertySymbol.Name))
				continue;

			bool isValueType = propertySymbol.Type.IsValueType
				&& propertySymbol.Type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T;
			builder.Add(new PropertyInfo(propertySymbol.Name, isValueType));
		}

		return builder.ToImmutable();
	}

	private static HashSet<string> GetExcludedProperties(ClassDeclarationSyntax classDeclaration)
	{
		HashSet<string> excluded = new(StringComparer.Ordinal);

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not "GenerateEquality" and not "GenerateEqualityAttribute")
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string value = argument.Expression.ToString().Trim('"');
					excluded.Add(value);
				}
			}
		}

		return excluded;
	}

	private static string GetAccessibility(ClassDeclarationSyntax classDeclaration)
	{
		foreach (SyntaxToken modifier in classDeclaration.Modifiers)
		{
			if (modifier.IsKind(SyntaxKind.PublicKeyword))
				return "public";
			if (modifier.IsKind(SyntaxKind.InternalKeyword))
				return "internal";
		}

		return "internal";
	}

	private readonly struct PropertyInfo(string name, bool isValueType)
	{
		public string Name { get; } = name;
		public bool IsValueType { get; } = isValueType;
	}
}
