// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Analyzers;
using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating the factory pattern for classes marked
/// with the <see cref="GenerateFactoryAttribute"/> attribute. The generated code
/// discovers all concrete implementations of a target interface at compile time
/// and emits a <c>Create(string key)</c> method that maps keys to concrete types.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FactoryGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(FactoryGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateFactoryAttribute).FullName;
	private static readonly string FactoryKeyAttributeName = typeof(GenerateFactoryKeyAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(
		SourceProductionContext context,
		(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;
		Compilation compilation = semanticModel.Compilation;

		if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
			return;

		// Get the interface type from the attribute
		INamedTypeSymbol? interfaceSymbol = GetInterfaceTypeFromAttribute(classSymbol);
		if (interfaceSymbol is null)
			return;

		if (interfaceSymbol.TypeKind != TypeKind.Interface)
		{
			Diagnostic diagnostic = Diagnostic.Create(
				DiagnosticDescriptors.FactoryRequiresInterfaceTypeDiagnostic,
				classDeclaration.Identifier.GetLocation(),
				classSymbol.Name,
				interfaceSymbol.Name);
			context.ReportDiagnostic(diagnostic);
			return;
		}

		// Discover all concrete implementations
		List<(INamedTypeSymbol Type, string Key)> implementations = [];
		HashSet<string> seenKeys = new(StringComparer.Ordinal);
		bool hasDuplicates = false;

		foreach (INamedTypeSymbol type in GetAllNamedTypes(compilation.GlobalNamespace))
		{
			if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsStatic)
				continue;

			if (!ImplementsInterface(type, interfaceSymbol))
				continue;

			if (!HasParameterlessConstructor(type))
				continue;

			string key = GetFactoryKey(type);

			if (!seenKeys.Add(key))
			{
				Diagnostic diagnostic = Diagnostic.Create(
					DiagnosticDescriptors.FactoryDuplicateKeyDiagnostic,
					classDeclaration.Identifier.GetLocation(),
					key,
					interfaceSymbol.Name);
				context.ReportDiagnostic(diagnostic);
				hasDuplicates = true;
				continue;
			}

			implementations.Add((type, key));
		}

		if (hasDuplicates)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);
		string interfaceName = interfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		string interfaceShortName = interfaceSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		AppendPartialClass(sb, className, accessibility, interfaceName, interfaceShortName, implementations);

		sb.AppendLine("}");

		context.AddSource($"{className}.Factory.g.cs", sb.ToString());
	}

	private static void AppendPartialClass(
		StringBuilder sb,
		string className,
		string accessibility,
		string interfaceFullName,
		string interfaceShortName,
		List<(INamedTypeSymbol Type, string Key)> implementations)
	{
		sb.AppendLine($"  {accessibility} partial class {className}");
		sb.AppendLine("  {");

		// Create method
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Creates an instance of <see cref=\"{interfaceShortName}\"/> based on the specified key.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine("    /// <param name=\"key\">The key identifying the implementation to create.</param>");
		sb.AppendLine($"    /// <returns>A new instance of <see cref=\"{interfaceShortName}\"/>.</returns>");
		sb.AppendLine("    /// <exception cref=\"System.ArgumentException\">Thrown when the key does not match any known implementation.</exception>");
		sb.AppendLine($"    public static {interfaceFullName} Create(string key)");
		sb.AppendLine("    {");
		sb.AppendLine("      return key switch");
		sb.AppendLine("      {");

		foreach ((INamedTypeSymbol type, string key) in implementations)
		{
			string fullTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			sb.AppendLine($"        \"{GeneratorHelpers.EscapeString(key)}\" => new {fullTypeName}(),");
		}

		sb.AppendLine("        _ => throw new System.ArgumentException($\"No implementation registered for key '{{key}}'.\", nameof(key)),");
		sb.AppendLine("      };");
		sb.AppendLine("    }");

		sb.AppendLine();

		// GetKeys method
		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Gets all registered factory keys.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine("    /// <returns>An enumerable of all registered keys.</returns>");
		sb.AppendLine("    public static System.Collections.Generic.IEnumerable<string> GetKeys()");
		sb.AppendLine("    {");

		foreach ((_, string key) in implementations)
		{
			sb.AppendLine($"      yield return \"{GeneratorHelpers.EscapeString(key)}\";");
		}

		if (implementations.Count == 0)
			sb.AppendLine("      yield break;");

		sb.AppendLine("    }");

		sb.AppendLine("  }");
	}

	private static INamedTypeSymbol? GetInterfaceTypeFromAttribute(INamedTypeSymbol classSymbol)
	{
		foreach (AttributeData attribute in classSymbol.GetAttributes())
		{
			if (attribute.AttributeClass?.ToDisplayString() != GeneratorAttributeName)
				continue;

			if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is INamedTypeSymbol typeSymbol)
				return typeSymbol;
		}

		return null;
	}

	private static string GetFactoryKey(INamedTypeSymbol type)
	{
		foreach (AttributeData attribute in type.GetAttributes())
		{
			if (attribute.AttributeClass?.ToDisplayString() != FactoryKeyAttributeName)
				continue;

			if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string key)
				return key;
		}

		return type.Name;
	}

	private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceSymbol)
	{
		foreach (INamedTypeSymbol iface in type.AllInterfaces)
		{
			if (SymbolEqualityComparer.Default.Equals(iface, interfaceSymbol))
				return true;
		}

		return false;
	}

	private static bool HasParameterlessConstructor(INamedTypeSymbol type)
	{
		foreach (IMethodSymbol constructor in type.Constructors)
		{
			if (constructor.Parameters.Length == 0 && constructor.DeclaredAccessibility == Accessibility.Public)
				return true;
		}

		// If no explicit constructors, the compiler provides a default parameterless one
		return type.Constructors.Length == 0;
	}

	private static IEnumerable<INamedTypeSymbol> GetAllNamedTypes(INamespaceSymbol namespaceSymbol)
	{
		foreach (INamedTypeSymbol type in namespaceSymbol.GetTypeMembers())
		{
			yield return type;

			foreach (INamedTypeSymbol nested in GetNestedTypes(type))
				yield return nested;
		}

		foreach (INamespaceSymbol child in namespaceSymbol.GetNamespaceMembers())
		{
			foreach (INamedTypeSymbol type in GetAllNamedTypes(child))
				yield return type;
		}
	}

	private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
	{
		foreach (INamedTypeSymbol nested in type.GetTypeMembers())
		{
			yield return nested;

			foreach (INamedTypeSymbol deepNested in GetNestedTypes(nested))
				yield return deepNested;
		}
	}
}
