// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating static <c>Read</c> and <c>Write</c> methods for classes marked
/// with the <see cref="GenerateIniFileAttribute"/> attribute. The generated methods support
/// serialization and deserialization of INI file content based on properties decorated with
/// <see cref="GenerateIniFileSectionAttribute"/> and <see cref="GenerateIniFileValueAttribute"/>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class IniFileGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(IniFileGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateIniFileAttribute).FullName;
	private static readonly string SectionAttributeName = typeof(GenerateIniFileSectionAttribute).FullName;
	private static readonly string ValueAttributeName = typeof(GenerateIniFileValueAttribute).FullName;
	private static readonly string[] LineBreakSeparators = ["\r\n", "\n"];

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => GeneratorHelpers.TransformClassSyntax(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		string className = classDeclaration.Identifier.Text;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);
		string stringComparison = GetStringComparison(classDeclaration, semanticModel);
		string sectionDelimiter = GetSectionDelimiter(classDeclaration, semanticModel);
		bool serializeComments = GetSerializeComments(classDeclaration);

		List<SectionInfo> sections = GetSections(classDeclaration, semanticModel, sectionDelimiter, serializeComments);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System;");
		sb.AppendLine("using System.Globalization;");
		sb.AppendLine("using System.Linq;");
		sb.AppendLine("using System.Text;");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		AppendReadMethod(sb, className, accessibility, sections, stringComparison);
		AppendWriteMethod(sb, className, sections, serializeComments);
		AppendLoadMethod(sb, className, sections);

		sb.AppendLine("  }");
		sb.AppendLine("}");

		context.AddSource($"{className}.g.cs", sb.ToString());
	}

	private static void AppendReadMethod(StringBuilder sb, string className, string accessibility, List<SectionInfo> sections, string stringComparison)
	{
		sb.AppendLine($"  {accessibility} partial class {className}");
		sb.AppendLine("  {");
		sb.AppendLine("    /// <summary>");
		sb.AppendLine("    /// Reads the specified INI file content and deserializes it into a new instance");
		sb.AppendLine($"    /// of <see cref=\"{className}\"/>.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine("    /// <param name=\"content\">The INI file string content to deserialize.</param>");
		sb.AppendLine($"    /// <returns>A new instance of <see cref=\"{className}\"/> populated from the INI content.</returns>");
		sb.AppendLine($"    public static {className} Read(string content)");
		sb.AppendLine("    {");
		sb.AppendLine($"      {className} result = new {className}();");
		sb.AppendLine("      string? currentSection = null;");
		sb.AppendLine("      string[] lines = content.Split(new[] { \"\\r\\n\", \"\\n\" }, StringSplitOptions.None);");
		sb.AppendLine();
		sb.AppendLine("      for (int i = 0; i < lines.Length; i++)");
		sb.AppendLine("      {");
		sb.AppendLine("        string line = lines[i].Trim();");
		sb.AppendLine();
		sb.AppendLine("        if (line.Length == 0 || line[0] == ';' || line[0] == '#')");
		sb.AppendLine("          continue;");
		sb.AppendLine();
		sb.AppendLine("        if (line[0] == '[' && line[line.Length - 1] == ']')");
		sb.AppendLine("        {");
		sb.AppendLine("          currentSection = line.Substring(1, line.Length - 2).Trim();");
		sb.AppendLine("          continue;");
		sb.AppendLine("        }");
		sb.AppendLine();
		sb.AppendLine("        int equalsIndex = line.IndexOf('=');");
		sb.AppendLine("        if (equalsIndex < 0)");
		sb.AppendLine("          continue;");
		sb.AppendLine();
		sb.AppendLine("        string key = line.Substring(0, equalsIndex).Trim();");
		sb.AppendLine("        string value = line.Substring(equalsIndex + 1).Trim();");
		sb.AppendLine();

		for (int s = 0; s < sections.Count; s++)
		{
			SectionInfo section = sections[s];
			string elsePrefix = s > 0 ? "else " : "";

			sb.AppendLine($"        {elsePrefix}if (string.Equals(currentSection, \"{section.SectionName}\", StringComparison.{stringComparison}))");
			sb.AppendLine("        {");

			if (section.NeedsInitialization)
			{
				sb.AppendLine($"          if (result.{section.PropertyPath} == null)");
				sb.AppendLine($"            result.{section.PropertyPath} = new {section.TypeName}();");
				sb.AppendLine();
			}

			for (int v = 0; v < section.Values.Count; v++)
			{
				ValueInfo value = section.Values[v];
				string valueElsePrefix = v > 0 ? "else " : "";

				sb.AppendLine($"          {valueElsePrefix}if (string.Equals(key, \"{value.KeyName}\", StringComparison.{stringComparison}))");
				sb.AppendLine($"            result.{section.PropertyPath}.{value.PropertyName} = {GetParseExpression(value, "value")};");
			}

			sb.AppendLine("        }");
		}

		sb.AppendLine();
		sb.AppendLine("      }");
		sb.AppendLine();
		sb.AppendLine("      return result;");
		sb.AppendLine("    }");
		sb.AppendLine();
	}

	private static void AppendWriteMethod(StringBuilder sb, string className, List<SectionInfo> sections, bool serializeComments)
	{
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Writes the specified <see cref=\"{className}\"/> instance to an INI file string.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    /// <param name=\"instance\">The <see cref=\"{className}\"/> instance to serialize.</param>");
		sb.AppendLine("    /// <returns>The serialized INI file string content.</returns>");
		sb.AppendLine($"    public static string Write({className} instance)");
		sb.AppendLine("    {");
		sb.AppendLine("      StringBuilder sb = new StringBuilder();");
		sb.AppendLine();

		for (int s = 0; s < sections.Count; s++)
		{
			SectionInfo section = sections[s];

			if (s > 0)
				sb.AppendLine("      sb.AppendLine();");

			string nullCheck = BuildNullCheck($"instance.{section.PropertyPath}");
			sb.AppendLine($"      if ({nullCheck})");
			sb.AppendLine("      {");

			if (serializeComments && section.Comment is not null)
				sb.AppendLine($"        sb.AppendLine(\"; {GeneratorHelpers.EscapeString(section.Comment)}\");");

			sb.AppendLine($"        sb.AppendLine(\"[{section.SectionName}]\");");

			foreach (ValueInfo value in section.Values)
			{
				if (serializeComments && value.Comment is not null)
					sb.AppendLine($"        sb.AppendLine(\"; {GeneratorHelpers.EscapeString(value.Comment)}\");");

				sb.AppendLine($"        sb.AppendLine(\"{value.KeyName}=\" + {GetToStringExpression($"instance.{section.PropertyPath}.{value.PropertyName}", value)});");
			}

			sb.AppendLine("      }");
		}

		sb.AppendLine();
		sb.AppendLine("      return sb.ToString();");
		sb.AppendLine("    }");
	}

	private static void AppendLoadMethod(StringBuilder sb, string className, List<SectionInfo> sections)
	{
		sb.AppendLine();
		sb.AppendLine("    /// <summary>");
		sb.AppendLine($"    /// Loads values from the specified <paramref name=\"other\"/> instance into this instance.");
		sb.AppendLine("    /// </summary>");
		sb.AppendLine($"    /// <param name=\"other\">The source <see cref=\"{className}\"/> instance to copy values from.</param>");
		sb.AppendLine($"    public void Load({className} other)");
		sb.AppendLine("    {");

		foreach (SectionInfo section in sections)
		{
			sb.AppendLine($"      if ({section.PropertyPath} != null && other.{section.PropertyPath} != null)");
			sb.AppendLine("      {");

			foreach (ValueInfo value in section.Values)
				sb.AppendLine($"        {section.PropertyPath}.{value.PropertyName} = other.{section.PropertyPath}.{value.PropertyName};");

			sb.AppendLine("      }");
		}

		sb.AppendLine("    }");
	}

	private static List<SectionInfo> GetSections(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel, string sectionDelimiter, bool serializeComments)
	{
		List<SectionInfo> sections = [];
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

		if (classSymbol is null)
			return sections;

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = null;
			foreach (AttributeData attr in propertySymbol.GetAttributes())
			{
				if (attr.AttributeClass?.ToDisplayString() == SectionAttributeName)
				{
					sectionAttribute = attr;
					break;
				}
			}

			if (sectionAttribute is null)
				continue;

			string sectionName = propertySymbol.Name;
			if (sectionAttribute.ConstructorArguments.Length > 0
				&& sectionAttribute.ConstructorArguments[0].Value is string explicitName
				&& !string.IsNullOrEmpty(explicitName))
			{
				sectionName = explicitName;
			}

			if (propertySymbol.Type is not INamedTypeSymbol sectionType)
				continue;

			bool needsInit = !HasInitializer(classDeclaration, propertySymbol.Name);
			string propertyPath = propertySymbol.Name;
			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			List<ValueInfo> values = GetValues(sectionType, serializeComments);

			sections.Add(new SectionInfo(
				PropertyName: propertySymbol.Name,
				PropertyPath: propertyPath,
				SectionName: sectionName,
				TypeName: sectionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
				NeedsInitialization: needsInit,
				Values: values,
				Comment: comment
			));

			CollectNestedSections(sections, sectionType, sectionName, propertyPath, sectionDelimiter, 1, serializeComments);
		}

		return sections;
	}

	private static void CollectNestedSections(List<SectionInfo> sections, INamedTypeSymbol parentType, string parentSectionName, string parentPropertyPath, string sectionDelimiter, int depth, bool serializeComments)
	{
		if (depth >= 8)
			return;

		foreach (ISymbol member in parentType.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? sectionAttribute = null;
			foreach (AttributeData attr in propertySymbol.GetAttributes())
			{
				if (attr.AttributeClass?.ToDisplayString() == SectionAttributeName)
				{
					sectionAttribute = attr;
					break;
				}
			}

			if (sectionAttribute is null)
				continue;

			string sectionName = propertySymbol.Name;
			if (sectionAttribute.ConstructorArguments.Length > 0
				&& sectionAttribute.ConstructorArguments[0].Value is string explicitName
				&& !string.IsNullOrEmpty(explicitName))
			{
				sectionName = explicitName;
			}

			if (propertySymbol.Type is not INamedTypeSymbol sectionType)
				continue;

			string fullSectionName = $"{parentSectionName}{sectionDelimiter}{sectionName}";
			string propertyPath = $"{parentPropertyPath}.{propertySymbol.Name}";
			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			List<ValueInfo> values = GetValues(sectionType, serializeComments);

			sections.Add(new SectionInfo(
				PropertyName: propertySymbol.Name,
				PropertyPath: propertyPath,
				SectionName: fullSectionName,
				TypeName: sectionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
				NeedsInitialization: false,
				Values: values,
				Comment: comment
			));

			CollectNestedSections(sections, sectionType, fullSectionName, propertyPath, sectionDelimiter, depth + 1, serializeComments);
		}
	}

	private static List<ValueInfo> GetValues(INamedTypeSymbol sectionType, bool serializeComments = false)
	{
		List<ValueInfo> values = [];

		foreach (ISymbol member in sectionType.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			AttributeData? valueAttribute = null;
			foreach (AttributeData attr in propertySymbol.GetAttributes())
			{
				if (attr.AttributeClass?.ToDisplayString() == ValueAttributeName)
				{
					valueAttribute = attr;
					break;
				}
			}

			if (valueAttribute is null)
				continue;

			string keyName = propertySymbol.Name;
			if (valueAttribute.ConstructorArguments.Length > 0
				&& valueAttribute.ConstructorArguments[0].Value is string explicitName
				&& !string.IsNullOrEmpty(explicitName))
			{
				keyName = explicitName;
			}

			string typeName = propertySymbol.Type.SpecialType switch
			{
				SpecialType.System_String => "string",
				SpecialType.System_Int32 => "int",
				SpecialType.System_Int64 => "long",
				SpecialType.System_Single => "float",
				SpecialType.System_Double => "double",
				SpecialType.System_Boolean => "bool",
				SpecialType.System_Decimal => "decimal",
				SpecialType.System_DateTime => "DateTime",
				_ => propertySymbol.Type.ToDisplayString()
			};

			bool isEnum = propertySymbol.Type.TypeKind == TypeKind.Enum;
			bool isFlagsEnum = false;
			string? enumFullName = null;

			if (isEnum)
			{
				enumFullName = propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				isFlagsEnum = propertySymbol.Type.GetAttributes()
					.Any(a => a.AttributeClass?.ToDisplayString() == "System.FlagsAttribute");
			}

			string? comment = serializeComments ? GetXmlSummaryComment(propertySymbol) : null;

			values.Add(new ValueInfo(
				PropertyName: propertySymbol.Name,
				KeyName: keyName,
				TypeName: typeName,
				IsEnum: isEnum,
				IsFlagsEnum: isFlagsEnum,
				EnumFullName: enumFullName,
				Comment: comment
			));
		}

		return values;
	}

	private static bool HasInitializer(ClassDeclarationSyntax classDeclaration, string propertyName)
	{
		foreach (MemberDeclarationSyntax member in classDeclaration.Members)
		{
			if (member is PropertyDeclarationSyntax propSyntax
				&& propSyntax.Identifier.Text == propertyName
				&& propSyntax.Initializer is not null)
			{
				return true;
			}
		}

		return false;
	}

	private static string GetParseExpression(ValueInfo value, string variableName)
	{
		if (value.IsEnum && value.EnumFullName is not null)
		{
			return value.IsFlagsEnum
				? $"({value.EnumFullName}){variableName}.Split(' ').Select(flag => ({value.EnumFullName})Enum.Parse(typeof({value.EnumFullName}), flag)).Aggregate(0, (current, flag) => current | (int)flag)"
				: $"({value.EnumFullName})Enum.Parse(typeof({value.EnumFullName}), {variableName})";
		}

		return value.TypeName switch
		{
			"string" => variableName,
			"int" => $"int.Parse({variableName}, CultureInfo.InvariantCulture)",
			"long" => $"long.Parse({variableName}, CultureInfo.InvariantCulture)",
			"float" => $"float.Parse({variableName}, CultureInfo.InvariantCulture)",
			"double" => $"double.Parse({variableName}, CultureInfo.InvariantCulture)",
			"bool" => $"bool.Parse({variableName})",
			"decimal" => $"decimal.Parse({variableName}, CultureInfo.InvariantCulture)",
			"DateTime" => $"DateTime.Parse({variableName}, CultureInfo.InvariantCulture)",
			_ => variableName,
		};
	}

	private static string GetToStringExpression(string expression, ValueInfo value)
	{
		if (value.IsEnum && value.EnumFullName is not null)
		{
			return value.IsFlagsEnum
				? $"string.Join(\" \", Enum.GetValues(typeof({value.EnumFullName})).Cast<{value.EnumFullName}>().Where(flag => flag != 0 && {expression}.HasFlag(flag)).Select(flag => flag.ToString()))"
				: $"{expression}.ToString()";
		}

		return value.TypeName switch
		{
			"string" => expression,
			"bool" => $"{expression}.ToString()",
			"DateTime" => $"{expression}.ToString(CultureInfo.InvariantCulture)",
			"int" or "long" or "float" or "double" or "decimal" =>
				$"{expression}.ToString(CultureInfo.InvariantCulture)",
			_ => $"{expression}?.ToString() ?? string.Empty",
		};
	}

	private static string GetStringComparison(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return "OrdinalIgnoreCase";

		foreach (AttributeData attr in classSymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() != GeneratorAttributeName)
				continue;

			if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int comparisonValue)
			{
				return comparisonValue switch
				{
					0 => "CurrentCulture",
					1 => "CurrentCultureIgnoreCase",
					2 => "InvariantCulture",
					3 => "InvariantCultureIgnoreCase",
					4 => "Ordinal",
					5 => "OrdinalIgnoreCase",
					_ => "OrdinalIgnoreCase"
				};
			}
		}

		return "OrdinalIgnoreCase";
	}

	private static string GetSectionDelimiter(ClassDeclarationSyntax classDeclaration, SemanticModel semanticModel)
	{
		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return ".";

		foreach (AttributeData attr in classSymbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() != GeneratorAttributeName)
				continue;

			if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value is string delimiterValue)
				return delimiterValue;
		}

		return ".";
	}

	private static bool GetSerializeComments(ClassDeclarationSyntax classDeclaration)
	{
		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not "GenerateIniFile" and not "GenerateIniFileAttribute")
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					if (argument.NameEquals?.Name.Identifier.Text == "SerializeComments")
					{
						string expressionText = argument.Expression.ToString();
						if (expressionText == "true")
							return true;
					}
				}
			}
		}

		return false;
	}

	private static string? GetXmlSummaryComment(ISymbol symbol)
	{
		foreach (SyntaxReference syntaxRef in symbol.DeclaringSyntaxReferences)
		{
			SyntaxNode node = syntaxRef.GetSyntax();

			if (!node.HasLeadingTrivia)
				continue;

			foreach (SyntaxTrivia trivia in node.GetLeadingTrivia())
			{
				if (trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
				{
					SyntaxNode? structure = trivia.GetStructure();
					if (structure is null)
						continue;

					foreach (SyntaxNode child in structure.ChildNodes())
					{
						if (child is not XmlElementSyntax xmlElement)
							continue;

						if (xmlElement.StartTag.Name.ToString() != "summary")
							continue;

						string content = xmlElement.Content.ToString();
						string[] lines = content.Split(LineBreakSeparators, StringSplitOptions.RemoveEmptyEntries);

						List<string> cleanLines = [];
						foreach (string line in lines)
						{
							string trimmed = line.Trim().TrimStart('/').Trim();
							if (trimmed.Length > 0)
								cleanLines.Add(trimmed);
						}

						if (cleanLines.Count > 0)
							return string.Join(" ", cleanLines);
					}
				}
			}
		}

		return null;
	}

	private static string BuildNullCheck(string propertyPath)
	{
		string[] segments = propertyPath.Split('.');
		if (segments.Length <= 2)
			return $"{propertyPath} != null";

		List<string> checks = [];
		for (int i = 1; i < segments.Length; i++)
		{
			checks.Add($"{string.Join(".", segments, 0, i + 1)} != null");
		}

		return string.Join(" && ", checks);
	}

	private sealed record SectionInfo(
		string PropertyName,
		string PropertyPath,
		string SectionName,
		string TypeName,
		bool NeedsInitialization,
		List<ValueInfo> Values,
		string? Comment = null
	);

	private sealed record ValueInfo(
		string PropertyName,
		string KeyName,
		string TypeName,
		bool IsEnum = false,
		bool IsFlagsEnum = false,
		string? EnumFullName = null,
		string? Comment = null
	);
}
