// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;
using BB84.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating notification properties for classes marked
/// with the <see cref="GenerateNotificationsAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NotificationsGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(NotificationsGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateNotificationsAttribute).FullName;
	private const string AttributeShortName = "GenerateNotifications";
	private const string AttributeFullName = "GenerateNotificationsAttribute";

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<SyntaxNode> provider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				fullyQualifiedMetadataName: GeneratorAttributeName,
				predicate: (node, _) => Predicate(node),
				transform: (context, _) => Transform(context.TargetNode))
			.Where(node => node is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private static bool Predicate(SyntaxNode node)
		=> node is ClassDeclarationSyntax;

	private static SyntaxNode Transform(SyntaxNode targetNode)
		=> (ClassDeclarationSyntax)targetNode;

	private void Execute(SourceProductionContext context, SyntaxNode syntaxNode)
	{
		ClassDeclarationSyntax classDeclaration = (ClassDeclarationSyntax)syntaxNode;

		(bool generatePropertyChanged, bool generatePropertyChanging, bool generateHasChanged) = GetAttributeOptions(classDeclaration);

		if (!generatePropertyChanged && !generatePropertyChanging)
			return;

		List<FieldDeclarationSyntax> members = [.. classDeclaration.Members
			.OfType<FieldDeclarationSyntax>()
			.Where(field => field is not null)];

		string className = classDeclaration.Identifier.Text;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GeneratorHelpers.GetAccessibility(classDeclaration);
		bool isSealed = classDeclaration.Modifiers.Any(SyntaxKind.SealedKeyword);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		AppendUsings(sb);
		AppendNamespaceStart(namespaceName, sb);
		AppendClassStart(sb, className, accessibility, generatePropertyChanged, generatePropertyChanging, generateHasChanged);
		AppendProperties(sb, members, generatePropertyChanged, generatePropertyChanging, generateHasChanged);
		AppendRaiseMethods(sb, generatePropertyChanged, generatePropertyChanging, isSealed);
		AppendClassEnd(sb);
		AppendNamespaceEnd(sb);

		context.AddSource($"{className}.g.cs", sb.ToString());
	}

	private static (bool propertyChanged, bool propertyChanging, bool hasChanged) GetAttributeOptions(ClassDeclarationSyntax classDeclaration)
	{
		bool propertyChanged = true;
		bool propertyChanging = true;
		bool hasChanged = false;

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not AttributeShortName and not AttributeFullName)
					continue;

				if (attribute.ArgumentList is null || attribute.ArgumentList.Arguments.Count == 0)
					return (propertyChanged, propertyChanging, hasChanged);

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string? paramName = argument.NameColon?.Name.Identifier.Text;
					string argText = argument.Expression.ToString();

					if (!bool.TryParse(argText, out bool value))
						continue;

					switch (paramName)
					{
						case "propertyChanged":
							propertyChanged = value;
							break;
						case "propertyChanging":
							propertyChanging = value;
							break;
						case "hasChanged":
							hasChanged = value;
							break;
						default:
							// Positional: first=propertyChanged, second=propertyChanging, third=hasChanged
							int index = attribute.ArgumentList.Arguments.IndexOf(argument);
							if (index == 0)
								propertyChanged = value;
							else if (index == 1)
								propertyChanging = value;
							else if (index == 2)
								hasChanged = value;
							break;
					}
				}

				return (propertyChanged, propertyChanging, hasChanged);
			}
		}

		return (propertyChanged, propertyChanging, hasChanged);
	}

	private static void AppendClassStart(StringBuilder sb, string className, string accessibility, bool propertyChanged, bool propertyChanging, bool hasChanged)
	{
		List<string> interfaces = [];

		if (propertyChanged)
			interfaces.Add("INotifyPropertyChanged");
		if (propertyChanging)
			interfaces.Add("INotifyPropertyChanging");

		string baseList = interfaces.Count > 0 ? $" : {string.Join(", ", interfaces)}" : string.Empty;

		sb.AppendLine($"    {accessibility} partial class {className}{baseList}");
		sb.AppendLine("    {");

		if (propertyChanged)
		{
			sb.AppendLine("        /// <inheritdoc/>");
			sb.AppendLine("        public event PropertyChangedEventHandler? PropertyChanged;");
			sb.AppendLine();
		}

		if (propertyChanging)
		{
			sb.AppendLine("        /// <inheritdoc/>");
			sb.AppendLine("        public event PropertyChangingEventHandler? PropertyChanging;");
			sb.AppendLine();
		}

		if (hasChanged)
		{
			sb.AppendLine("        private bool _hasChanged;");
			sb.AppendLine();
			sb.AppendLine("        /// <summary>");
			sb.AppendLine("        /// Gets or sets a value indicating whether the object has been changed.");
			sb.AppendLine("        /// </summary>");
			sb.AppendLine("        public bool HasChanged");
			sb.AppendLine("        {");
			sb.AppendLine("            get => _hasChanged;");
			sb.AppendLine("            set");
			sb.AppendLine("            {");
			sb.AppendLine("                if (_hasChanged != value)");
			sb.AppendLine("                {");
			if (propertyChanging)
				sb.AppendLine("                    RaisePropertyChanging(nameof(HasChanged));");
			sb.AppendLine("                    _hasChanged = value;");
			if (propertyChanged)
				sb.AppendLine("                    RaisePropertyChanged(nameof(HasChanged));");
			sb.AppendLine("                }");
			sb.AppendLine("            }");
			sb.AppendLine("        }");
			sb.AppendLine();
		}
	}

	private static void AppendProperties(StringBuilder sb, List<FieldDeclarationSyntax> members, bool propertyChanged, bool propertyChanging, bool hasChanged)
	{
		sb.AppendLine(string.Join(Environment.NewLine, members.SelectMany(member =>
				member.Declaration.Variables.Select(variable =>
				{
					string fieldName = variable.Identifier.Text;
					string fieldType = $"{member.Declaration.Type}";
					string propertyName = FieldNameToPropertyName(fieldName);

					StringBuilder propertySb = new();
					propertySb.AppendLine($"        public {fieldType} {propertyName}");
					propertySb.AppendLine("        {");
					propertySb.AppendLine($"            get => {fieldName};");
					propertySb.AppendLine("            set");
					propertySb.AppendLine("            {");
					propertySb.AppendLine($"                if ({fieldName} != value)");
					propertySb.AppendLine("                {");
					if (propertyChanging)
						propertySb.AppendLine($"                    RaisePropertyChanging(nameof({propertyName}));");
					propertySb.AppendLine($"                    {fieldName} = value;");
					if (propertyChanged)
						propertySb.AppendLine($"                    RaisePropertyChanged(nameof({propertyName}));");
					if (hasChanged)
						propertySb.AppendLine("                    HasChanged = true;");
					propertySb.AppendLine("                }");
					propertySb.AppendLine("            }");
					propertySb.Append("        }");

					return propertySb.ToString();
				}))));
	}

	private static void AppendRaiseMethods(StringBuilder sb, bool propertyChanged, bool propertyChanging, bool isSealed)
	{
		string methodModifier = isSealed ? "private" : "protected virtual";

		if (propertyChanging)
		{
			sb.AppendLine();
			sb.AppendLine("        /// <summary>");
			sb.AppendLine("        /// Raises the <see cref=\"PropertyChanging\"/> event to notify subscribers that a property");
			sb.AppendLine("        /// is about to change.");
			sb.AppendLine("        /// </summary>");
			sb.AppendLine("        /// <param name=\"propertyName\">The name of the property that is changing.</param>");
			sb.AppendLine($"        {methodModifier} void RaisePropertyChanging(string propertyName)");
			sb.AppendLine("            => PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));");
		}

		if (propertyChanged)
		{
			sb.AppendLine();
			sb.AppendLine("        /// <summary>");
			sb.AppendLine("        /// Raises the <see cref=\"PropertyChanged\"/> event to notify subscribers that a property");
			sb.AppendLine("        /// has changed.");
			sb.AppendLine("        /// </summary>");
			sb.AppendLine("        /// <param name=\"propertyName\">The name of the property that has changed.</param>");
			sb.AppendLine($"        {methodModifier} void RaisePropertyChanged(string propertyName)");
			sb.AppendLine("            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
		}
	}

	private static void AppendClassEnd(StringBuilder sb)
	{
		sb.AppendLine("    }");
	}

	private static void AppendNamespaceEnd(StringBuilder sb)
	{
		sb.AppendLine("}");
	}

	private static void AppendNamespaceStart(string classNamespace, StringBuilder sb)
	{
		sb.AppendLine($"namespace {classNamespace}");
		sb.AppendLine("{");
	}

	private static void AppendUsings(StringBuilder sb)
	{
		sb.AppendLine("using System;");
		sb.AppendLine("using System.ComponentModel;");
		sb.AppendLine();
	}

	/// <summary>
	/// Converts a field name to a property name by removing any leading underscores
	/// and capitalizing the first letter.
	/// </summary>
	/// <param name="fieldName">The field name to convert.</param>
	/// <returns>The converted property name.</returns>
	private static string FieldNameToPropertyName(string fieldName)
	{
		if (fieldName.StartsWith("_", StringComparison.OrdinalIgnoreCase))
			fieldName = fieldName[1..];
		return $"{char.ToUpperInvariant(fieldName[0])}{fieldName[1..]}";
	}
}
