// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a <c>ToString()</c> override for classes marked
/// with the <see cref="GenerateToStringAttribute"/> attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ToStringGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(ToStringGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateToStringAttribute).FullName;

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => Transform(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private static (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? Transform(GeneratorAttributeSyntaxContext context)
		=> context.TargetNode is not ClassDeclarationSyntax classSyntax ? null : ((ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?)(classSyntax, context.SemanticModel);

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GetAccessibility(classDeclaration);

		HashSet<string> excludedProperties = GetExcludedProperties(classDeclaration);
		ImmutableArray<string> properties = GetPublicProperties(classSymbol, excludedProperties);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		AppendPartialClass(sb, className, accessibility, properties);

		sb.AppendLine("}");

		context.AddSource($"{className}.ToString.g.cs", sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<string> properties)
	{
		sb.AppendLine($"  {accessibility} partial class {className}");
		sb.AppendLine("  {");
		sb.AppendLine("    /// <inheritdoc/>");
		sb.AppendLine($"    public override string ToString()");
		sb.AppendLine("    {");

		if (properties.Length == 0)
			sb.AppendLine($"      return \"{className} {{ }}\";");
		else
			sb.AppendLine($"      return $\"{className} {{{{ {BuildFormatString(properties)} }}}}\";");

		sb.AppendLine("    }");
		sb.AppendLine("  }");
	}

	private static string BuildFormatString(ImmutableArray<string> properties)
	{
		StringBuilder format = new();

		for (int i = 0; i < properties.Length; i++)
		{
			if (i > 0)
				format.Append(", ");

			format.Append($"{properties[i]} = {{{properties[i]}}}");
		}

		return format.ToString();
	}

	private static ImmutableArray<string> GetPublicProperties(INamedTypeSymbol classSymbol, HashSet<string> excludedProperties)
	{
		ImmutableArray<string>.Builder builder = ImmutableArray.CreateBuilder<string>();

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			if (propertySymbol.DeclaredAccessibility != Accessibility.Public)
				continue;

			if (propertySymbol.IsStatic || propertySymbol.IsWriteOnly || propertySymbol.GetMethod is null)
				continue;

			if (excludedProperties.Contains(propertySymbol.Name))
				continue;

			builder.Add(propertySymbol.Name);
		}

		return builder.ToImmutable();
	}

	private static HashSet<string> GetExcludedProperties(ClassDeclarationSyntax classDeclaration)
	{
		HashSet<string> excluded = new(StringComparer.Ordinal);

		foreach (AttributeListSyntax attributeList in classDeclaration.AttributeLists)
		{
			foreach (AttributeSyntax attribute in attributeList.Attributes)
			{
				string name = attribute.Name.ToString();

				if (name is not "GenerateToString" and not "GenerateToStringAttribute")
					continue;

				if (attribute.ArgumentList is null)
					continue;

				foreach (AttributeArgumentSyntax argument in attribute.ArgumentList.Arguments)
				{
					string value = argument.Expression.ToString().Trim('"');
					excluded.Add(value);
				}
			}
		}

		return excluded;
	}

	private static string GetAccessibility(ClassDeclarationSyntax classDeclaration)
	{
		foreach (SyntaxToken modifier in classDeclaration.Modifiers)
		{
			if (modifier.IsKind(SyntaxKind.PublicKeyword))
				return "public";
			if (modifier.IsKind(SyntaxKind.InternalKeyword))
				return "internal";
		}

		return "internal";
	}
}
