// Copyright: 2026 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Collections.Immutable;
using System.Text;

using BB84.SourceGenerators.Attributes;
using BB84.SourceGenerators.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BB84.SourceGenerators;

/// <summary>
/// Responsible for generating a <c>Validate()</c> method for classes marked
/// with the <see cref="GenerateValidatorAttribute"/> attribute. The generated method
/// scans properties for data annotation attributes and emits direct validation checks.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ValidatorGenerator : IIncrementalGenerator
{
	private static readonly string GeneratorName = typeof(ValidatorGenerator).FullName;
	private static readonly string GeneratorAttributeName = typeof(GenerateValidatorAttribute).FullName;

	private const string RequiredAttributeName = "System.ComponentModel.DataAnnotations.RequiredAttribute";
	private const string RangeAttributeName = "System.ComponentModel.DataAnnotations.RangeAttribute";
	private const string StringLengthAttributeName = "System.ComponentModel.DataAnnotations.StringLengthAttribute";
	private const string MinLengthAttributeName = "System.ComponentModel.DataAnnotations.MinLengthAttribute";
	private const string MaxLengthAttributeName = "System.ComponentModel.DataAnnotations.MaxLengthAttribute";
	private const string RegularExpressionAttributeName = "System.ComponentModel.DataAnnotations.RegularExpressionAttribute";

	/// <inheritdoc/>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<(ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?> provider =
			context.SyntaxProvider
				.ForAttributeWithMetadataName(
					fullyQualifiedMetadataName: GeneratorAttributeName,
					predicate: static (node, _) => node is ClassDeclarationSyntax,
					transform: static (ctx, _) => Transform(ctx))
				.Where(static result => result is not null);

		context.RegisterSourceOutput(provider, Execute);
	}

	private static (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? Transform(GeneratorAttributeSyntaxContext context)
	{
		return context.TargetNode is not ClassDeclarationSyntax classSyntax ? null : ((ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)?)(classSyntax, context.SemanticModel);
	}

	private void Execute(SourceProductionContext context, (ClassDeclarationSyntax ClassSyntax, SemanticModel SemanticModel)? input)
	{
		if (input is null)
			return;

		ClassDeclarationSyntax classDeclaration = input.Value.ClassSyntax;
		SemanticModel semanticModel = input.Value.SemanticModel;

		INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
		if (classSymbol is null)
			return;

		string className = classSymbol.Name;
		string namespaceName = classDeclaration.GetNamespace();
		string accessibility = GetAccessibility(classDeclaration);

		ImmutableArray<PropertyValidationInfo> validatedProperties = GetValidatedProperties(classSymbol);

		List<(string Accessibility, string Name)> outerClasses = GetOuterClasses(classDeclaration);

		StringBuilder sb = new();

		sb.AppendAutoGeneratedWarning(GeneratorName);
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine("using System.Text.RegularExpressions;");
		sb.AppendLine();
		sb.AppendLine($"namespace {namespaceName}");
		sb.AppendLine("{");

		int baseIndent = 1;
		foreach ((string outerAccessibility, string outerName) in outerClasses)
		{
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}{outerAccessibility} partial class {outerName}");
			sb.AppendLine($"{indent}{{");
			baseIndent++;
		}

		AppendPartialClass(sb, className, accessibility, validatedProperties, baseIndent);

		for (int i = outerClasses.Count - 1; i >= 0; i--)
		{
			baseIndent--;
			string indent = new(' ', baseIndent * 2);
			sb.AppendLine($"{indent}}}");
		}

		sb.AppendLine("}");

		string hintName = outerClasses.Count > 0
			? $"{string.Join(".", outerClasses.Select(o => o.Name))}.{className}.Validator.g.cs"
			: $"{className}.Validator.g.cs";

		context.AddSource(hintName, sb.ToString());
	}

	private static void AppendPartialClass(StringBuilder sb, string className, string accessibility, ImmutableArray<PropertyValidationInfo> validatedProperties, int indentLevel = 1)
	{
		string indent = new(' ', indentLevel * 2);
		string innerIndent = new(' ', (indentLevel + 1) * 2);
		string bodyIndent = new(' ', (indentLevel + 2) * 2);

		sb.AppendLine($"{indent}{accessibility} partial class {className}");
		sb.AppendLine($"{indent}{{");
		sb.AppendLine($"{innerIndent}/// <summary>");
		sb.AppendLine($"{innerIndent}/// Validates the current instance and returns a list of validation errors.");
		sb.AppendLine($"{innerIndent}/// </summary>");
		sb.AppendLine($"{innerIndent}/// <returns>A list of validation error messages. An empty list indicates a valid instance.</returns>");
		sb.AppendLine($"{innerIndent}public List<string> Validate()");
		sb.AppendLine($"{innerIndent}{{");
		sb.AppendLine($"{bodyIndent}List<string> errors = new List<string>();");

		foreach (PropertyValidationInfo property in validatedProperties)
		{
			foreach (ValidationRule rule in property.Rules)
			{
				AppendValidationRule(sb, property.Name, property.TypeName, property.IsCollection, property.IsArray, rule, bodyIndent);
			}
		}

		sb.AppendLine($"{bodyIndent}return errors;");
		sb.AppendLine($"{innerIndent}}}");
		sb.AppendLine($"{indent}}}");
	}

	private static void AppendValidationRule(StringBuilder sb, string propertyName, string typeName, bool isCollection, bool isArray, ValidationRule rule, string bodyIndent)
	{
		sb.AppendLine();

		switch (rule.Kind)
		{
			case ValidationKind.Required:
				AppendRequiredValidation(sb, propertyName, typeName, rule, bodyIndent);
				break;
			case ValidationKind.Range:
				AppendRangeValidation(sb, propertyName, isCollection, isArray, rule, bodyIndent);
				break;
			case ValidationKind.StringLength:
				AppendStringLengthValidation(sb, propertyName, rule, bodyIndent);
				break;
			case ValidationKind.MinLength:
				AppendMinLengthValidation(sb, propertyName, rule, bodyIndent);
				break;
			case ValidationKind.MaxLength:
				AppendMaxLengthValidation(sb, propertyName, rule, bodyIndent);
				break;
			case ValidationKind.RegularExpression:
				AppendRegularExpressionValidation(sb, propertyName, rule, bodyIndent);
				break;
		}
	}

	private static void AppendRequiredValidation(StringBuilder sb, string propertyName, string typeName, ValidationRule rule, string bodyIndent)
	{
		string message = rule.ErrorMessage ?? $"The {propertyName} field is required.";

		if (typeName is "string" or "string?")
		{
			sb.AppendLine($"{bodyIndent}if (string.IsNullOrEmpty({propertyName}))");
		}
		else
		{
			sb.AppendLine($"{bodyIndent}if ({propertyName} == null)");
		}

		sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
	}

	private static void AppendRangeValidation(StringBuilder sb, string propertyName, bool isCollection, bool isArray, ValidationRule rule, string bodyIndent)
	{
		if (isCollection)
		{
			string countAccessor = isArray ? "Length" : "Count";
			string message = rule.ErrorMessage ?? $"The field {propertyName} must have between {rule.MinValue} and {rule.MaxValue} elements.";

			sb.AppendLine($"{bodyIndent}if ({propertyName} != null && ({propertyName}.{countAccessor} < {rule.MinValue} || {propertyName}.{countAccessor} > {rule.MaxValue}))");
			sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
		}
		else
		{
			string message = rule.ErrorMessage ?? $"The field {propertyName} must be between {rule.MinValue} and {rule.MaxValue}.";

			sb.AppendLine($"{bodyIndent}if ({propertyName} < {rule.MinValue} || {propertyName} > {rule.MaxValue})");
			sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
		}
	}

	private static void AppendStringLengthValidation(StringBuilder sb, string propertyName, ValidationRule rule, string bodyIndent)
	{
		if (rule.MinValue is not null)
		{
			string minMessage = rule.ErrorMessage ?? $"The field {propertyName} must be a string with a minimum length of {rule.MinValue} and a maximum length of {rule.MaxValue}.";

			sb.AppendLine($"{bodyIndent}if ({propertyName} != null && ({propertyName}.Length < {rule.MinValue} || {propertyName}.Length > {rule.MaxValue}))");
			sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(minMessage)}\");");
		}
		else
		{
			string message = rule.ErrorMessage ?? $"The field {propertyName} must be a string with a maximum length of {rule.MaxValue}.";

			sb.AppendLine($"{bodyIndent}if ({propertyName} != null && {propertyName}.Length > {rule.MaxValue})");
			sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
		}
	}

	private static void AppendMinLengthValidation(StringBuilder sb, string propertyName, ValidationRule rule, string bodyIndent)
	{
		string message = rule.ErrorMessage ?? $"The field {propertyName} must be a string or collection with a minimum length of {rule.MinValue}.";

		sb.AppendLine($"{bodyIndent}if ({propertyName} != null && {propertyName}.Length < {rule.MinValue})");
		sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
	}

	private static void AppendMaxLengthValidation(StringBuilder sb, string propertyName, ValidationRule rule, string bodyIndent)
	{
		string message = rule.ErrorMessage ?? $"The field {propertyName} must be a string or collection with a maximum length of {rule.MaxValue}.";

		sb.AppendLine($"{bodyIndent}if ({propertyName} != null && {propertyName}.Length > {rule.MaxValue})");
		sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
	}

	private static void AppendRegularExpressionValidation(StringBuilder sb, string propertyName, ValidationRule rule, string bodyIndent)
	{
		string message = rule.ErrorMessage ?? $"The field {propertyName} must match the regular expression '{EscapeString(rule.Pattern!)}'.";

		sb.AppendLine($"{bodyIndent}if ({propertyName} != null && !Regex.IsMatch({propertyName}, @\"{EscapeVerbatimString(rule.Pattern!)}\"))");
		sb.AppendLine($"{bodyIndent}  errors.Add(\"{EscapeString(message)}\");");
	}

	private static ImmutableArray<PropertyValidationInfo> GetValidatedProperties(INamedTypeSymbol classSymbol)
	{
		ImmutableArray<PropertyValidationInfo>.Builder builder = ImmutableArray.CreateBuilder<PropertyValidationInfo>();

		foreach (ISymbol member in classSymbol.GetMembers())
		{
			if (member is not IPropertySymbol propertySymbol)
				continue;

			if (propertySymbol.DeclaredAccessibility != Accessibility.Public)
				continue;

			if (propertySymbol.IsStatic || propertySymbol.GetMethod is null)
				continue;

			ImmutableArray<ValidationRule>.Builder rules = ImmutableArray.CreateBuilder<ValidationRule>();

			foreach (AttributeData attribute in propertySymbol.GetAttributes())
			{
				string? attributeName = attribute.AttributeClass?.ToDisplayString();

				if (attributeName is null)
					continue;

				ValidationRule? rule = attributeName switch
				{
					RequiredAttributeName => ParseRequiredAttribute(attribute),
					RangeAttributeName => ParseRangeAttribute(attribute),
					StringLengthAttributeName => ParseStringLengthAttribute(attribute),
					MinLengthAttributeName => ParseMinLengthAttribute(attribute),
					MaxLengthAttributeName => ParseMaxLengthAttribute(attribute),
					RegularExpressionAttributeName => ParseRegularExpressionAttribute(attribute),
					_ => null
				};

				if (rule is not null)
					rules.Add(rule);
			}

			if (rules.Count > 0)
			{
				string typeName = propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
				bool isCollection = IsCollectionType(propertySymbol.Type);
				bool isArray = propertySymbol.Type.TypeKind == TypeKind.Array;
				builder.Add(new PropertyValidationInfo(propertySymbol.Name, typeName, isCollection, isArray, rules.ToImmutable()));
			}
		}

		return builder.ToImmutable();
	}

	private static ValidationRule ParseRequiredAttribute(AttributeData attribute)
	{
		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.Required) { ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseRangeAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 2)
			return null;

		string? minValue = args[0].Value?.ToString();
		string? maxValue = args[1].Value?.ToString();

		if (minValue is null || maxValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.Range) { MinValue = minValue, MaxValue = maxValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseStringLengthAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? maxValue = args[0].Value?.ToString();

		if (maxValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		int? minLengthValue = GetNamedArgumentValue<int>(attribute, "MinimumLength");
		string? minValue = minLengthValue?.ToString(System.Globalization.CultureInfo.InvariantCulture);

		return new ValidationRule(ValidationKind.StringLength) { MaxValue = maxValue, MinValue = minValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseMinLengthAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? minValue = args[0].Value?.ToString();

		if (minValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.MinLength) { MinValue = minValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseMaxLengthAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? maxValue = args[0].Value?.ToString();

		if (maxValue is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.MaxLength) { MaxValue = maxValue, ErrorMessage = errorMessage };
	}

	private static ValidationRule? ParseRegularExpressionAttribute(AttributeData attribute)
	{
		ImmutableArray<TypedConstant> args = attribute.ConstructorArguments;

		if (args.Length < 1)
			return null;

		string? pattern = args[0].Value?.ToString();

		if (pattern is null)
			return null;

		string? errorMessage = GetNamedArgumentValue<string>(attribute, "ErrorMessage");

		return new ValidationRule(ValidationKind.RegularExpression) { Pattern = pattern, ErrorMessage = errorMessage };
	}

	private static T? GetNamedArgumentValue<T>(AttributeData attribute, string name)
	{
		foreach (KeyValuePair<string, TypedConstant> namedArgument in attribute.NamedArguments)
		{
			if (namedArgument.Key == name && namedArgument.Value.Value is T value)
				return value;
		}

		return default;
	}

	private static string GetAccessibility(ClassDeclarationSyntax classDeclaration)
	{
		foreach (SyntaxToken modifier in classDeclaration.Modifiers)
		{
			if (modifier.IsKind(SyntaxKind.PublicKeyword))
				return "public";
			if (modifier.IsKind(SyntaxKind.InternalKeyword))
				return "internal";
		}

		return "internal";
	}

	private static List<(string Accessibility, string Name)> GetOuterClasses(ClassDeclarationSyntax classDeclaration)
	{
		List<(string Accessibility, string Name)> outerClasses = [];
		SyntaxNode? parent = classDeclaration.Parent;

		while (parent is ClassDeclarationSyntax outerClass)
		{
			outerClasses.Add((GetAccessibility(outerClass), outerClass.Identifier.Text));
			parent = outerClass.Parent;
		}

		outerClasses.Reverse();
		return outerClasses;
	}

	private static bool IsCollectionType(ITypeSymbol type)
	{
		if (type.TypeKind == TypeKind.Array)
			return true;

		if (type.SpecialType == SpecialType.System_String)
			return false;

		foreach (INamedTypeSymbol iface in type.AllInterfaces)
		{
			if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
				return true;
		}

		return type is INamedTypeSymbol namedType && namedType.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T;
	}

	private static string EscapeString(string value)
		=> value.Replace("\\", "\\\\").Replace("\"", "\\\"");

	private static string EscapeVerbatimString(string value)
		=> value.Replace("\"", "\"\"");

	private enum ValidationKind
	{
		Required,
		Range,
		StringLength,
		MinLength,
		MaxLength,
		RegularExpression
	}

	private sealed class ValidationRule(ValidatorGenerator.ValidationKind kind)
	{
		public ValidationKind Kind { get; } = kind;
		public string? MinValue { get; set; }
		public string? MaxValue { get; set; }
		public string? Pattern { get; set; }
		public string? ErrorMessage { get; set; }
	}

	private readonly struct PropertyValidationInfo(string name, string typeName, bool isCollection, bool isArray, ImmutableArray<ValidatorGenerator.ValidationRule> rules)
	{
		public string Name { get; } = name;
		public string TypeName { get; } = typeName;
		public bool IsCollection { get; } = isCollection;
		public bool IsArray { get; } = isArray;
		public ImmutableArray<ValidationRule> Rules { get; } = rules;
	}
}
